### ISSUE TITLE
CT: If there are manual checks involved, collecting contact information to notify user of progress

### ISSUE THREAD

**Issue by kateiw** [alphagov/verify-local-patterns#102]
We should only collect contact information if the application requires manual checks.

If we are using an automated photo checker then we should be able to confirm the application success and give a date they should receive their pass by immediately.

If we cannot use an automated photo checker then the collection of contact details should come after the photo upload stage, before the confirmation page.

**Comment by suryanaga** [comment]
Was this fixed with #53?

**Comment by kateiw** [comment]
No I don't think so - we still need to figure out how the photos will be checked and if we can use an adaptation of the HO passport photo checker.

We're avoiding a renewals reminder on CT.

**Comment by suryanaga** [comment]
Cool, that makes sense.
