### ISSUE TITLE
PP: add to section Did the user recently move in? 

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#104]
Should we be asking when the user moved in the property in addition to if they moved since the the old permit was issued.

comment in regard to this from Sunderland CC:

Because users are allowed 5 permits per property and charges increase for each additional permit, we would want to ask the question when the user moved into the property after we knew they were at an eliglible address.  We could then determine if they were a new resident and cancel any previous permits and ensure the right amount is charged, or tell the customer that they cannot have a permit as the maximum for that property had been reached.  We have to filter out residents of HMO properties and deal with their applications manually so this should only be traditional households who reach this point

**Comment by kaydale** [comment]
@EUzkuraityte 
![screen shot 2017-01-31 at 13 45 46](https://cloud.githubusercontent.com/assets/20561170/22467216/a3756280-e7bb-11e6-9334-b841a90d8514.png)

Doesn't this page cover that? Its section "7d. Did the user recently move in?"

It then takes you to: https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/moved-in

**Comment by suryanaga** [comment]
@EUzkuraityte Ok to close this issue?

**Comment by suryanaga** [comment]
Closing this until further justification is given.
