### ISSUE TITLE
PP: advise on users moving outside the borough or within (from one CPZ to another)

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#108]
Comment from B&H: Cancelling old permits and next steps - We need to encourage customers moving within Brighton to surrender old permits - the patten does not cover this

could we think of the best place in the user journey where we could incorporate this advice?

**Comment by kaydale** [comment]
@EUzkuraityte If not a digital permit, this would be good information to include in the letter that will accompany the permit itself. So maybe we should add a step for "send the user the physical permit"

**Comment by EUzkuraityte** [comment]
Sounds good!

**Comment by suryanaga** [comment]
@kaydale What response is this waiting on?

**Comment by kaydale** [comment]
@sanjaypoyzer It was waiting a response from me - to move it into ready to do.

**Comment by suryanaga** [comment]
lol ok

**Comment by suryanaga** [comment]
@EUzkuraityte Reading over this, I'm not really sure I understand why it's needed. Surely the old permit will be cancelled? Won't all permits be checked anyway?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer if the LA has no integration between council tax and parking permit system then they wouldn't know that a user has moved and the used would continue using the parking permit until its expiry date. That's why need to let users know that they must inform the LA when moving out of the borough or within (if it affects the CPZ).

**Comment by suryanaga** [comment]
I'm not sure that's the best way of addressing that problem. It relies on people notifying the council that they have moved, which they aren't likely to do.

If the council is not able to integrate council and parking permits systems in any real way, they could manually search the permits system for the user's address when the user stops paying council tax. This is extra effort on the council side, but not as much extra effort as it would be on the user's side. (It's also the council's responsibility to make the service as little effort for the user as possible.)

**Comment by suryanaga** [comment]
Closing this issue for now to clean up the board, but feel free to re-open if you get extra justification.
