### ISSUE TITLE
Both: Chose a format of index pages

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#121]
It is not clear what should be user facing terminology & transactions (aka included in the service) VS and what is for us to communicate with LAs about how the pattern should work.

**Comment by suryanaga** [comment]
@kaydale Not sure I understand this. Could you give an example?

**Comment by kaydale** [comment]
@sanjaypoyzer This was about the amount of content on the guidance pages aka: https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit

we discussed this this morning but agreed that waiting till we are done iterating to figure out the best way to present this page

**Comment by suryanaga** [comment]
Cool, keep in then for a To Do later

**Comment by suryanaga** [comment]
Gonna go for the same format as https://www.gov.uk/service-manual/design/addresses
