### ISSUE TITLE
option for screen where no payment is required

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#141]
https://verify-local-patterns.herokuapp.com/pay/choose-payment

Hi @sanjaypoyzer , could you create an alternative page or amend this one to allow the user to bypass payment if they have mitigating circumstances, i.e. are a blue badge holder, live in a HMO property, etc.

**Comment by suryanaga** [comment]
@EUzkuraityte Yep, but I need to understand more about what those different mitigating circumstances are exactly. We also need to think about how a user proves each of those circumstances.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer so there are only few thatI know of:
I am a current blue badge holder
I live in Housing of Multiple Occupation property
I am a council tenant

I suppose it's not universal across all of LAs, and the evidence/routes to provide it would be dependant on LAs business rules

**Comment by suryanaga** [comment]
@EUzkuraityte Ok cool, if we can collect some more info then I'm happy to put it in.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer no probs, will do some research a little later and consult other pilot participants to get you a more comprehensive list

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer 
so depending on the council, a user would not be charged if they:
I am a current blue badge holder
I live in Housing of Multiple Occupation property
I am applying for the 1st household permit
I am a first person in my household to apply for a parking permit
I drive an eco vehicle

**Comment by suryanaga** [comment]
@EUzkuraityte going to find any more and turn them all into seperate issues

**Comment by EUzkuraityte** [comment]
Closing this as it is a duplicate of #313
