### ISSUE TITLE
Users need a good incentive to choose Verify

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#143]
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/prove-identity

Hi @sanjaypoyzer,
would you be able to change this line about Verify 'You'll receive your permit faster if you verify your identity with GOV.UK Verify.' to sth else like ' If you choose to proceed with GOV.UK Verify, you'll be able to reuse our logins to access central government services' or some other better line!

It was raised by some pilot participants that their current processes are actually faster now and also the time to receive a permit will not be impacted by the channel used to submit the application.

**Comment by suryanaga** [comment]
@EUzkuraityte I'm not sure there's precedent for saying to users they can reuse their Verify identity in other services on those screens, and I'm not sure it's something there's agreement that we definitely want to do in general. 

The time to receive a permit should be affected, as without Verify there is going to be manual processing of documents. Not really sure how it could be the case that Verify _doesn't_ speed up the time to receive a permit.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer Some LAs issue a permit without checking the docs and then do all the checks retrospectively. Other LAs don't even ask for any proof if a user can provide a c-tax number, etc so to claim that with Verify the process is definitely shorter is not factually true. It can be shorter or it can be way longer. 

Can you thing of a line for promoting Verify that would apply across LAs?

**Comment by suryanaga** [comment]
@EUzkuraityte Well there's a difference between claiming that the process of applying is shorter (which in many cases it won't be) and claiming that the time for the permit to be issued/arrive is shorter (which except in the case where it's being issued before the checks, it will be).

If there isn't a genuine advantage to users, then we shouldn't really promote Verify just for the sake of it. So it comes down to what the advantage to users is, if it's not getting their thing quicker.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer I had a chat internally with the team and the consensus is that the log ins will be reusable.. I think it's worth putting it up and the reusability of credentials across local and central is a massive selling point..

as for the process being quicker - could be quicker, could be the same. Will need to consult out pilot participants on this, as I really don't know.

**Comment by petegale** [comment]
We need to be careful with language here. Reusing credentials is not something that we encourage (as in using the same username and password), or language that's used anywhere in the hub. 

I spoke to Ant about the copy shown below. He's happy for us to go with that.
![screen shot 2017-04-06 at 15 15 50](https://cloud.githubusercontent.com/assets/2970019/24759028/0e315306-1adc-11e7-9c36-835e364e638d.png)

**Comment by petegale** [comment]
Pushing this back into TODO, as it needs work before coming back to research questions

**Comment by suryanaga** [comment]
Hmm... Wondering if it also needs the Verify logo if we use that language. (Was something I was thinking about doing anyway.)

**Comment by suryanaga** [comment]
I'm going to close this issue as people are pretty consistently choosing Verify in research now.
