### ISSUE TITLE
Some councils need extra vehicle details for enforcement purposes

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#145]
@sanjaypoyzer 

At the end of the section, could you add 'If required for enforcement purposes, a local authority may also ask for make, model and colour of the vehicle'

this was raised to us as part of gating template and we were told that without this information a user can challenge a parking ticket

**Comment by suryanaga** [comment]
Yep. Can add this.

**Comment by suryanaga** [comment]
@EUzkuraityte Is this still a thing if we're using the DVLA API?

**Comment by joanneSouthern** [comment]
we need to upload V5 - for compliance with our policy

**Comment by sanjaypoyzer** [comment]
@joanneSouthern Can we get the policy changed?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer just to continue the original thread..

We may be able to use VES API for this info and to calculate the permit price but we need a-to give user the option not to use it b-if reg not found or if the user chooses not to use VES look up, we need the fields to capture this info

**Comment by joanneSouthern** [comment]
not with elections coming up, it would take too long

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer here are the responses we got. Councils want to be using none or a combination of the listed items for enforcement purposes (4.2). The prototype should allow councils to localise this functionality and request this information from the user via VES API or manually. 

4.2 What vehicle details do you need to ask the user via a VES API or manually for enforcement purposes?
- Vehicle make
- Vehicle colour
- Vehicle registration number (entered by the user)
- Vehicle model
- Vehicle status
- None

**Comment by suryanaga** [comment]
Let's dig in further to why councils need this information so that we can explain to users why it's being used.

**Comment by EUzkuraityte** [comment]
@joanneSouthern @GWSunderland @OxfordshireCountyCouncil @danblundell 

would you be able to provide a bit more info / reasoning on why we're asking users to give vehicle information for enforcement purposes? What's the underpinning need here?

**Comment by GWSunderland** [comment]
I believe we collect this to help enforcement officers determine whether a permit is genuine.  The make, model and colour is not displayed on our permit but enforcement officers can access this information to verify the authenticity of a permit if they suspect one has been tampered with.

**Comment by suryanaga** [comment]
@EUzkuraityte So to confirm, DVLA's API response should include:

 - Vehicle make
 - Vehicle colour
 
As the below screenshot shows, the records do not include a "Vehicle model" entry.

Why do councils need "Vehicle status" for enforcement?

![image](https://cloud.githubusercontent.com/assets/4106955/25897568/4fef1698-3580-11e7-8df9-792205132b2d.png)

**Comment by kaydale** [comment]
@sanjaypoyzer  

I can confirm that my car is black ;)

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer Yes, i think this sounds correct. I assume that if a car is not taxed, then it's not legal to drive it, hence, need to know the status.

**Comment by suryanaga** [comment]
@EUzkuraityte So does that mean if the car is not taxed the council will not issue it with a permit? What about if it has a SORN?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer we can ask Colin on Monday about what they do with SORNs, but I don't think we've observed any users having a car and wanting a parking permit for an off road car..

**Comment by danblundell** [comment]
If it's SORN, it can't be on the road can it? So it wouldn't need a permit?

**Comment by suryanaga** [comment]
Weird, I wrote that question, then had that same thought and thought I deleted it before submitting. Obviously I'm just going crazy.

Still, would be good to know what happens if the car isn't taxed. I assume they refuse the permit?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer I just got an email from DVLA re: use of VES API and they've been a little slow with shifting the service onto the new platform. Therefore, they're not able to take onto even one new RP. We'll have a catch up in a few month's time but it definitely does not align with our timescales and we won't be able to have this functionality in time. 

In light of this, can we:
1 [change this page to introduce additional information fields](https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/enter-reg) as drop downs. FYI, you can find the required information for drop downs in [this spreadsheet](https://drive.google.com/open?id=0B_rqDnauwjr8c1BkM2tBX0pHUzQ). Let me know if you need anything in addition. 
2 introduce an option for the user to go to [DVLA site and check this information](https://vehicleenquiry.service.gov.uk/) if they don't have it ready
3 Update [this page](https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/confirm-vehicle-details) to that it no longer says we received this info from DVLA 

I'm copying in @lizziebruce for this as she can advice on the content copy for both of these pages

**Comment by lizziebruce** [comment]
What I'm creating, as I understand it from above discussion...

https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/enter-reg
1. Field label copy for:
Vehicle make
Vehicle colour
2. Instructions for the user to go to DVLA site and check this information if they don't have it ready

https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/confirm-vehicle-details
3. delete "we received this info from DVLA" (and replace with something else?)

**Comment by lizziebruce** [comment]
So...

**Enter reg page**

For councils who want extra enforcement details:

![screen shot 2017-06-28 at 15 26 33](https://user-images.githubusercontent.com/27814324/27642283-34c8e90e-5c16-11e7-859a-1b5033136254.png)


[Not done the drop down functionality. Need @sanjaypoyzer / dev help with this!
Car make – is this drop down / free text / autotext?
Car colours: Beige, black, blue, bronze, brown, buff, cream, gold, green, grey, ivory, maroon, orange, pink, purple, red, silver, turquoise, white and yellow.]


For councils that don't it's still:

![screen shot 2017-06-28 at 15 06 39](https://user-images.githubusercontent.com/27814324/27642291-389b006c-5c16-11e7-8431-28e4393bdd4b.png)

**Confirm vehicle details page**

For councils who want extra enforcement details:

![screen shot 2017-06-28 at 15 44 11](https://user-images.githubusercontent.com/27814324/27643875-317f39f2-5c1a-11e7-901d-c53badc215ee.png)

For councils that don't it's still:

![screen shot 2017-06-28 at 15 54 54](https://user-images.githubusercontent.com/27814324/27643885-38ab8712-5c1a-11e7-9321-ac285a0b175d.png)

**Comment by EUzkuraityte** [comment]
@lizziebruce amazing work! The only bit that I'd change is not showing the confirm vehicle details page for councils that don't ask additional details as the user would not have entered anything prior ..

**Comment by lizziebruce** [comment]
@EUzkuraityte thanks! Should this screen simply say confirm registration number then, or alternatively there be functionality for the reg number they input to appear on the previous screen for them to check, i.e. in case of typos etc?

**Comment by EUzkuraityte** [comment]
@lizziebruce I think we probs don't need an entire page just to confirm what they've just entered. Would go with your latter proposition or just adding the reg number to the 'check before you pay' page.

**Comment by lizziebruce** [comment]
@EUzkuraityte thanks, let's get @sanjaypoyzer involved for councils that don't need additional details. Just to doublecheck, are there 2 options or 3? My content fix was for scenarios 1. and 2. below but it from your comments it sounds like either there could be 1. 2. and 3. or that it's only 1. and 3. 
1. Council asks for make and colour from user
2. Council looks up make and colour from DVLA and asks user to confirm
2. Council doesn't ask for or look up make and colour

**Comment by joanneSouthern** [comment]
Northumberland, at the moment we just ask for the reg, however we like the fact the DVLA brings back make and colour, it provides a extra check to the users that they have entered the correct reg

**Comment by suryanaga** [comment]
@joanneSouthern The DVLA API won't be available in the timescales of this project.

In response to Lizzie's 3 options, the option 2 will not be available - So there will only be option 1 and 3.

**Comment by lizziebruce** [comment]
@sanjaypoyzer hey, this issue wasn't showing up on the Project Board. @Egle couldn't find it either. Then we moved a different card and it suddenly showed up! Something similar happened with a CT issue this morning. Does Github have weevils?

**Comment by lizziebruce** [comment]
Fixed but need Sanjay's help with the Next button coding.

**Council requires make and colour**
![screen shot 2017-07-04 at 13 08 52](https://user-images.githubusercontent.com/27814324/27829553-08ddfa52-60ba-11e7-85e8-6f4234b8335b.png)
Next screen is
![screen shot 2017-07-04 at 13 08 20](https://user-images.githubusercontent.com/27814324/27829559-0daf2740-60ba-11e7-8283-b3ad5b85da40.png)

**Council doesn't**
![screen shot 2017-07-04 at 12 51 27](https://user-images.githubusercontent.com/27814324/27829576-1f0ae880-60ba-11e7-8a9c-1b6520af983c.png)
Skips confirm details screen but can check reg number on this later screen
![screen shot 2017-07-04 at 10 40 48](https://user-images.githubusercontent.com/27814324/27829581-2530ff7e-60ba-11e7-8cf7-c043d5cef3c4.png)

**Comment by suryanaga** [comment]
@lizziebruce Come grab me to work on this if you want, or put in a pull request and I'll take a look.

**Comment by lizziebruce** [comment]
@sanjaypoyzer I've added this on the prototype now (sorry was editing master so no PR). The Next button goes to the next screen as per below. 

Ask for make colour
<img width="519" alt="screen shot 2017-07-07 at 15 42 51" src="https://user-images.githubusercontent.com/27814324/27962826-fa12f518-632a-11e7-839d-a695ff11c010.png">
<img width="538" alt="screen shot 2017-07-07 at 15 42 57" src="https://user-images.githubusercontent.com/27814324/27962829-fbeeff08-632a-11e7-850a-a977f0002b58.png">

Don't ask for make colour
<img width="526" alt="screen shot 2017-07-07 at 15 33 55" src="https://user-images.githubusercontent.com/27814324/27962841-02191b66-632b-11e7-8cef-be059719edbc.png">
<img width="551" alt="screen shot 2017-07-07 at 15 34 01" src="https://user-images.githubusercontent.com/27814324/27962848-0619d372-632b-11e7-943e-a70d6156831f.png">

Ideally the No radio button on the Confirm details screen should take the user back to the Enter reg page. But it doesn't at the moment.

**Comment by lizziebruce** [comment]
@EUzkuraityte FYI here's the vehicle makes & colours dropdown functionality that Sanjay has added:

<img width="719" alt="screen shot 2017-07-07 at 15 21 40" src="https://user-images.githubusercontent.com/27814324/27962996-81f64278-632b-11e7-99c8-4ce771116d5e.png">
<img width="618" alt="screen shot 2017-07-07 at 15 22 14" src="https://user-images.githubusercontent.com/27814324/27962988-7af07822-632b-11e7-9769-be45b43e9445.png">

**Comment by suryanaga** [comment]
Ok for larger things like this, we really need to have a review process with PRs.

I don't think there's any need for a confirm vehicle details in either instance here.

**Comment by lizziebruce** [comment]
@sanjaypoyzer But it's all screenshotted out in the issue above with you tagged on it... You should have commented then that you didn't think it was the right approach.

**Comment by EUzkuraityte** [comment]
closing this as we no longer recommend asking users for the additional info
