### ISSUE TITLE
Users need to check if permits are available near their address before verifying

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#146]
Hi @sanjaypoyzer 
I need your advice on this, as the feedback we got is this:
'We would need to check the eligibility to park (is there available permits) before the customer goes through the verification process - we expect that customers who have verified to then find out they can’t get a permit, would be (probably rightly) annoyed and cause an increase in complaints'

It makes perfect sense to me but I'm not sure this is something we've had to deal with before. Can you think of any privacy  implications? Essentially a user can claim to live somewhere and the tool would return the information against the asserted address. - I'm not 100% sure if this is ok and, in theory, could make it easier to commit fraud. What are your thoughts?

**Comment by suryanaga** [comment]
@EUzkuraityte I think this is a valid user need, reworded to reflect as such - But I think it should probably be a localised option so we can discuss whether or not to test with it in the Argleton version.

**Comment by sanjaypoyzer** [comment]
This came up as a real need in the Con Travel research, but I want to talk to the Notify team about it a bit more.
