### ISSUE TITLE
Helping users upload photos

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#147]
**Issue:** All of the assistance focusses on how to take a good photo, however in research, many of the issues we heard of were more to do with how to get a photo onto a computer or tablet and than how to upload it. I suspect that we may not be addressing the most important need here.

**Impact:** In discovery research we heard many users mention that problems uploading photos had led them to abandon similar transactions.

**Evidence:** This need was recorded in the user research journey map here: http://www.localdigitalcoalition.uk/wp-content/uploads/2017/01/Concessionary-travel-journey-map.pdf

**Comment by irinapencheva** [comment]
Will close this issue as it's covered by #314 and other issues around photoupload including #458, #347
