### ISSUE TITLE
Both: Technical components content

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#15]
Need to add some content to describe the technical components underpinning the connection with Verify.

**Comment by suryanaga** [comment]
The 'service SAML' is the part of the Relying Party (council)'s service which sends SAML to Verify. There are many free and open source third party tools councils can utilise to serve this function.

1. Service SAML creates Auth request
2. Service SAML session store records auth request ID
3. Matching service receives matching request
4. Matching service responds 'no match'
(Here if we were matching, the service would interact with a data store, but for new applications this is not needed.)
5.  Matching service receives unknown user account creation - responds 'success'
6. Service SAML receives assertion with name and address
7. Service SAML session store check request ID to make sure it's the right request
8. Relying Party (council's website) receives user details and shows user to confirm.

**Comment by suryanaga** [comment]
@gdsamit Is the above correct?

**Comment by gdsamit** [comment]
Service creates **Authn request** SAML

Service records authn request ID in its session store

Matching service receives matching request
Matching service responds 'no match'

(Here if we were matching, the service would interact with a data store, but for new applications this is not needed.)

Matching service receives unknown user account creation - responds 'success'

Service receives assertion with name and address

Service SAML session store check request ID to make sure it's the right request

Relying Party (council's website) receives user details and shows user to confirm.

**Comment by gdsamit** [comment]
(Sorry - missed your request in a sea of mail from github...)

**Comment by suryanaga** [comment]
Closing this issue as it's being served outside of the pattern.
