### ISSUE TITLE
CT: Improve formulation of user need

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#151]
Currently says: 'As someone who is eligible to travel for free [...] So that I am able to travel for free'

**Comment by irinapencheva** [comment]
@petegale

**Comment by suryanaga** [comment]
Should say "As someone who is old enough for free travel, I need a bus pass so that I can prove I'm eligible to ride for free on a bus."

**Comment by irinapencheva** [comment]
As someone who is old enough for a bus pass
I need to apply for a concessionary travel permit 
So that I am able to travel for free
