### ISSUE TITLE
Do users read service start page & can we move the how to use pass (incl. validity) to confirmation of pass issued page?

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#152]

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 24 26](https://cloud.githubusercontent.com/assets/2970019/23556734/820cfd9c-0025-11e7-9d26-f0967f3389f0.png)

**Comment by irinapencheva** [comment]
Evidence from latest round of UR still suggests users don't read the start page #459 and #457
