### ISSUE TITLE
CT: Capturing users contact details should happen before the step 'sending the bus pass to user'.

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#156]
Propose to split step '9. Sending the bus pass to the user' and reorder as follows: step 9. Confirming application is complete' followed by '10. contacting users',  followed by  '11. sending the bus pass to the user' 
This is to align easier scaling of the pattern for the use of Notify where the confirmation email and letter is potentially sent by Notify

**Comment by suryanaga** [comment]
@irinapencheva I think this part might have changed since you added this issue. Ok to close?

**Comment by irinapencheva** [comment]
Yep, thanks!
