### ISSUE TITLE
Both: Add average wait time to receive permit/pass

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#16]
Irina & Egle to gather data on this.

**Comment by suryanaga** [comment]
@irinapencheva @euzkuraityte Do we have any data on this yet?

**Comment by irinapencheva** [comment]
@sanjaypoyzer for ConTravel it varies between getting it immediately (if on F2F) or around 3-5 WD. I would put 5 WD on the main prototype and say that's a point they can change on their local prototype

**Comment by suryanaga** [comment]
Oops, just fixed this on master. Ah well, there goes my flawless git best practice
