### ISSUE TITLE
PP: minor edit to prototype - verification failed page

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#160]
@sanjaypoyzer 

Hi, could you replace 'apply online for a older person's bus pass' with 'apply online for a parking permit' here :https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/verification-failed

**Comment by suryanaga** [comment]
[Done](https://github.com/alphagov/verify-local-patterns/blob/master/app/views/service-patterns/parking-permit/example-service/verification-failed.html)
