### ISSUE TITLE
Changes to Confirm address and eligibility

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#161]
@sanjaypoyzer 

Hi, could you shorten the section 5 a bit to look like below. There's some repetition with section 6 that I took out. 

GOV.UK Verify will send the council the user's address, as known by the user's chosen identity provider. On returning from the GOV.UK Verify process, the council should ask the user to confirm whether or not this is their current address.
**See the example page asking users to confirm their name and address**

If the user says the address returned is not correct, they are likely to be a new resident whose address has not been updated with their identity provider. The user should then be asked to enter their current address and warned that they must not enter false information.
**See the example page asking users to enter their current address**

If the permit is physical, councils will get extra confidence in the address by mailing the permit to the address given. Councils should mention they'll be using the address for this purpose on the confirmation page.

If the permit is digital and councils want extra confidence of eligibility, they can issue a temporary permit for a shorter time period, for example 3 months. After this time, the user's identity provider should have the new address and the user can reapply.

**Comment by suryanaga** [comment]
@EUzkuraityte If I understand correctly, you just want me to remove:

> At this point the council should check whether or not the person or the household already has a parking permit. For some councils this may affect the price, for others it might mean the user can not have another permit.
