### ISSUE TITLE
move section Contacting users to before Enter vehicle details

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#162]
Hi @sanjaypoyzer 

could you move section 10? it makes more sense to capture user's  contact details after checking their address and eligibility...

**Comment by suryanaga** [comment]
@EUzkuraityte Not sure I understand - Section 10 is after all checks, it's right at the end of the journey

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer I think we spoke about it in person. It makes for a more coherent flow if we ask user details about them (Verify stuff plus contact info), then about their car and finally the payment info.

Rather than info about them, then the car, then payment, then more info about them...

Not a major issue if you can't change it, just IMPO this would look better

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer also, we need to be asking for people's contact info as part of the application (I think this is applicable to both prototypes) in case the council needs to follow up with the applicant 

BTW, not sure if it's a bug or sth, but link in 'Request a confirmation email.' is not working...
