### ISSUE TITLE
Add more info to confirmation page

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#164]
hi @sanjaypoyzer 

As discussed, could you edit the section to say the below and also add a link to the prototype confirmation page?

After payment, the user needs to receive a confirmation of payment and an acknowledgement that their application has been successful. They should also receive information about:

- how the permit will be enforced
- how long they will need to wait for a permit to be posted to them
- if they can pick up their permit from a council office to get it faster and where from
- if they can print a temporary permit themselves while they wait for a permanent one
- advice on how customers can park without their permit until they receive it
**See the example confirmation page.**

If the payment cannot be accepted or if the application fails for some reason (i.e. times out) the user should be shown an on-screen message that specifies the next steps a user should take to continue with the application.

The service should ask the user how they would like to receive this confirmation of payment, offering the choice of email, letter or text. **See the example page on how to do this.**

In the future, councils will be able to send this confirmation using GOV.UK Notify.

**Comment by suryanaga** [comment]
@EUzkuraityte Does this issue still apply or is it outdated?

**Comment by suryanaga** [comment]
Most of these were already done in separate issues aside from:

## how the permit will be enforced 

Have now done this. Documented in #275.

## if they can pick up their permit from a council office to get it faster and where from 

This is more complex than just adding a line to the page. We need to ask the user this question earlier in the flow. It should be a council option, not all councils will need it. For that reason I've created issue #276.
