### ISSUE TITLE
Do users understand what is a good quality picture? Do they need additional help

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#167]

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 25 11](https://cloud.githubusercontent.com/assets/2970019/23556765/9d372642-0025-11e7-8591-e40305106f93.png)

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 25 51](https://cloud.githubusercontent.com/assets/2970019/23556805/beb777ea-0025-11e7-9b36-2ea6ceea0689.png)

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 26 07](https://cloud.githubusercontent.com/assets/2970019/23556813/c662041a-0025-11e7-8e0f-6b7502bb9736.png)

**Comment by irinapencheva** [comment]
Most have a clear understanding of what is acceptable. Users tend to scan the photo criteria and then assume that these are the same as those for a passport. 

As a result, some additional criteria are assumed:
“No smiling”

![screen shot 2017-04-26 at 11 48 05](https://cloud.githubusercontent.com/assets/24913176/25430872/40d9e968-2a76-11e7-869f-7c911991150b.png)

**Comment by petegale** [comment]
Users understand basics of what is required for the photo, but need help with uploading and cropping their photos
