### ISSUE TITLE
CT: Move existing bus pass check to below age and address confirmation

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#170]
In the pattern it says

>If the user is not eligible because they already have a pass, the council should tell them and also link to the 'Renew or replace your bus pass' service. The page should also include a link to contact the council if the user believes there has been a mistake.

>See the page telling the user they are not eligible because they already have a pass

Is this a thing? It will require the councils to match the user's identity to a bus pass database, but I think we're not doing matching?

**Comment by suryanaga** [comment]
@irinapencheva ^^

**Comment by irinapencheva** [comment]
This is a think, but they don't need to do ID matching to establish that - it will be a back-end eligibility/ duplicate records check once Verify has provided the identity

**Comment by suryanaga** [comment]
Right ok, so it is something they will build?

**Comment by irinapencheva** [comment]
Yes, it's part of their tech stack/ integration with back-end

**Comment by suryanaga** [comment]
@irinapencheva Ok, so I've revised the content of this a little bit because I was moving around some stuff that's near it.

If you can just confirm you're happy with this then we can close this issue. (It's now point 6 on the [pattern page](http://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel).)

>Do you already have a bus pass?
If the user has been successfully verified, The council will receive the user's name, address, and date of birth from GOV.UK Verify.

>At this point the council should check whether or not they have a bus pass against their records. If they already have a pass, they should tell them they are not eligible to apply for a new one, but they can renew or replace a lost or stolen one with the 'Renew or replace your bus pass' service. The page should also include a link to contact the council if the user believes there has been a mistake.

>See the page telling the user they are not eligible because they already have a pass

**Comment by irinapencheva** [comment]
@sanjaypoyzer - happy with the wording but this step should happen after the user has confirmed age and address (otherwise the Verify info cannot be used). So can you make this to be step 8.

Can you also change in the first sentence the typo - should be lowercase 't' in 'the council'
