### ISSUE TITLE
CT: Service pattern step for photo upload needs to be reworded to reflect latest process

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#175]

**Comment by suryanaga** [comment]
"Users can upload a digital passport style photograph for use on the bus pass, but they may need to be instructed how. The council website should ask the user whether or not they need instructions, and then step them through the process if they do." - Reword this.

**Comment by irinapencheva** [comment]
Suggested: "Users can upload a digital photograph of themselves for use on the bus pass, but they need to be given guidance on the required quality of the photograph. The council website should ask the user whether or not they want to take a picture using the device they are using, or by uploading a photograph that they already have."
