### ISSUE TITLE
Nonverify start page should be more like contravel nonverify start page

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#183]
The nonverify start page content needs changing to accomodate the fact the user has already seen a start page by this point

**Comment by kaydale** [comment]
@sanjaypoyzer Does this look ok? 

## Apply for a resident's parking permit without using GOV.UK Verify

You can still apply online for a parking permit, but you'll need to scan and upload some documents.

##  To apply online you will need to provide:

- Proof of address, such as a council tax bill or a recent utility bill or a tenancy agreement or a mortgage statement

You'll need to scan in and upload these documents, and we'll check them after your application.
