### ISSUE TITLE
Users need to feel the level of identity verification of information entered is proportionate for the service

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#190]
Users believe that the requirements for identity verification are unusually stringent for a concessionary travel pass, and a few reported they would abandon the process as a result.

As with the previous issue, helping user to understand why they are being verified, and the benefits of that may help.

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 17 30](https://cloud.githubusercontent.com/assets/2970019/23556428/8963c78e-0024-11e7-8f20-08c25e5cbc97.png)

**Comment by irinapencheva** [comment]
also related to #197 - should be addressed as part of start page and why Verify is used for this service

**Comment by suryanaga** [comment]
Will see this in lab next week, hopefully should be addressed by changing the service to LOA1.

**Comment by petegale** [comment]
This issue was only reported by a single user in Round 3 (and this user appeared to be an extreme edge case.) Going to say that this has been addressed by changing to LOA1
