### ISSUE TITLE
Users need motivation to choose Verify

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#192]
**Impact:** Some were less likely to select the verified route

**Evidence:** Some users read that their permit would take longer, yet still chose the un-verified route. For these users, delivery time was not an important factor.

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 15 00](https://cloud.githubusercontent.com/assets/2970019/23556331/316542f6-0024-11e7-9b3a-a060ecf710a6.png)

**Comment by irinapencheva** [comment]
This and issue #193 should be addressed at start page as part of benefits of going through the Verify route

**Comment by suryanaga** [comment]
@irinapencheva The start page already has too much content, which is why all the information about the Verify choice is introduced in it's own page.

**Comment by suryanaga** [comment]
This should be addressed by #240.
