### ISSUE TITLE
Users need to know if they'll have to upload documents in their chosen prove ID route

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#193]
**Impact:** Users were less likely to select the verified route

**Evidence:** Some users who chose the unverified route without intending to, were more positive about the verified route than those who had not.

“Of this is good, you don’t have to upload any documents” User 4

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 13 58](https://cloud.githubusercontent.com/assets/2970019/23556305/10275cbe-0024-11e7-893d-bee1d7eee2d3.png)

**Comment by suryanaga** [comment]
I think this should be addressed by #240.
