### ISSUE TITLE
At the first page of the Verify hub, some users reported confusion about how this related to applying for a bus pass

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#197]
Some were further confused by the presence of the identity providers.

Giving users a better understanding of why they are being verified may improve this.

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 09 46](https://cloud.githubusercontent.com/assets/2970019/23556152/7e042eca-0023-11e7-937a-e35dc6aea50d.png)

**Comment by suryanaga** [comment]
Closing this as a duplicate of #190.
