### ISSUE TITLE
Councils need photos to be cropped to a passport photo proportions

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#203]
Impact: These photos may not be suitable and this may prevent completion of the application.

Evidence: Users were asked to take photos that met the criteria set out. Of the five photos taken, two did not meet criteria for both framing and background.

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 14 59 14](https://cloud.githubusercontent.com/assets/2970019/23555831/54e88f00-0022-11e7-8066-c541f997d786.png)

**Comment by suryanaga** [comment]
We think we'll meet this need in Beta with an automatic photo cropping component.

**Comment by irinapencheva** [comment]
@sanjaypoyzer - are we going to provide that?

**Comment by suryanaga** [comment]
@irinapencheva We need to discuss this with a dev / tech arch. There's quite a few different ways it could be done.

**Comment by irinapencheva** [comment]
@sanjaypoyzer - so can we reopen and put in Icebox?

**Comment by suryanaga** [comment]
@irinapencheva No, because we know it can technically be done, and fairly easily. From an Alpha perspective, I'm confident this isn't an issue.
