### ISSUE TITLE
Add explainer page about payment before user chooses payment option

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#207]
Before being asked to choose a payment option, there should be a page getting users to confirm what they are about to do, mainly because the payment screens are often controlled by an outside body but also because users are used to payment screens feeling different to the rest of a service.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer on this page, would you also be able to offer the user an option to let the council know that they have mitigating circumstances that would allow them to obtain a permit free of charge? I feel like we've already had this discussion, so apols if I'm duplicating!

**Comment by suryanaga** [comment]
@EUzkuraityte That will involve adding proof of that concession - This feels big enough that it should really be a separate issues (and also will block this issue being closed if we don't make it separate).
