### ISSUE TITLE
Remove breadcrumbs from payment pages

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#208]
To make them feel slightly more away from the rest of the service.

Also worth exploring if the rest of the layout can be minimised at all.

**Comment by suryanaga** [comment]
@kaydale You'll need to write a nunjucks `if` in the  `lib/argleton_template.html` to do this.

**Comment by kaydale** [comment]
@sanjaypoyzer Not done that before - probs best if you take that one today as I won't be in the office to get help ;)

**Comment by suryanaga** [comment]
@kaydale Have a go at searching in that file for the word "breadcrumbs" and see if you can work it out :)

**Comment by kaydale** [comment]
@sanjaypoyzer when you say lib/argleton_template.html do you mean layout_argelton.html?

**Comment by kaydale** [comment]
@sanjaypoyzer Here is my best guess without being taught anything about how to do nunjucks stuff 

{% if pageTitle = "Enter card details" or "Confirm your payment"%}
Do not {{ breadcrumb  }}
  {% endif %}
but I literally have no idea how to do that in real life.

**Comment by suryanaga** [comment]
@kaydale You're way too close for me to give you the answer :)

**Comment by kaydale** [comment]
@sanjaypoyzer so some of that needs to be in this:  

<title>{{council.name}}: {{serviceName}} {{" " if startPage else " - " + pageTitle }} </title>

??

**Comment by suryanaga** [comment]
@kaydale You shouldn't need to touch that line I don't think, that's the title of the page.

**Comment by kaydale** [comment]
@sanjaypoyzer 
Damn I thought that was why the start page didn't have breadcrumbs and everything else does :( 
I really am stuck now :(

**Comment by kaydale** [comment]
@sanjaypoyzer you going to have to give me a clue

{% if pageTitle = "Enter card details" - {{breadcrumb}}{% endif %}
{% if pageTitle = "Confirm your payment" - {{breadcrumb}}{% endif %}

**Comment by suryanaga** [comment]
@kaydale It's the other way round - You want to do it if the page title doesn't include either of those things. Have a look at `else` - https://mozilla.github.io/nunjucks/templating.html

**Comment by kaydale** [comment]
I have been studying that page hard but I'm the kind of learner who needs to talk me though it with someone. 

{% if pageTitle = "" + {{breadcrumb}}%}
{% else pageTitle = ("Enter card details", "Confirm your payment")  - {{breadcrumb}}%}
{% endif %}

@sanjaypoyzer could park it till Monday and you can teach me or you can do this one...

**Comment by suryanaga** [comment]
@kaydale Sure, let's do that :)
