### ISSUE TITLE
non verify route function to upload evidence

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#210]
Hi @sanjaypoyzer 

could you add a document upload function for a non- verify route. 
As a starter could you include this advice:

To apply for a parking permit, you need to provide us with:

- your vehicle registration document (V5C). The address has to match your residency address. If you have recently moved and have not updated your V5C, you can [do it here](https://www.gov.uk/change-name-address-v5c). 
- proof of residency (tenancy agreement or utility bill). The document has to clearly show your name and address.

These documents can be uploaded as a scan or a photograph. 

Upload button
Upload button

**Comment by suryanaga** [comment]
@EUzkuraityte The proof of address is in there already. Is the V5C still needed even with DVLA lookup?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer Yes, it is because DVLA look up is for VES not KADOE info.. so it provides nothing on the vehicle keeper information

**Comment by suryanaga** [comment]
@EUzkuraityte The Verify route won't return vehicle keeper information either. If a council needs to know that, it will need to be in both routes.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer Yup, see: https://github.com/alphagov/verify-local-patterns/issues/211

**Comment by suryanaga** [comment]
@EUzkuraityte Ok, closing this issue then and let's stick to that one.
