### ISSUE TITLE
Users need to apply for multiple resident's permits at the same time

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#224]
**Impact:** Users wanting to apply for multiple passes would have to complete multiple applications.

**Evidence:** Some users reported past applications for multiple permits and for some this remained an issue and a concern throughout the transaction.

**Comment by suryanaga** [comment]
- Users who just want visitors permits should use a different (lower level of assurance) service.
 - Users who want visitors permits *and* residents permits should be able to get them in one flow. 
 - Users who want multiple residents permits (if council allows) should be able to get them in one flow.

**Comment by EUzkuraityte** [comment]
I assume a new step in the user journey is needed in between 
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/resident-choice
and
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/resident-start

that asks the user what types and how many permits he wants to apply for

**Comment by suryanaga** [comment]
Adding a seperate issue for visitors permits here - #300.

**Comment by EUzkuraityte** [comment]
![image](https://cloud.githubusercontent.com/assets/20285115/24917346/c549b852-1ed4-11e7-9077-f38488d61163.png)

**Comment by ingasiler** [comment]
![image](https://cloud.githubusercontent.com/assets/19390851/25748735/0833d06c-31a4-11e7-9133-ba7781ddc994.png)

**Comment by ingasiler** [comment]
Users need to get visitors (guests) permits in the same transaction as resident's permits #300

**Comment by suryanaga** [comment]
Reopening this until we've seen it in research.
