### ISSUE TITLE
Users need to know where permits could be used before they applied for one

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#226]
**Impact:** Users may be unwilling to start an application if they only know about the permit's validity at a single postcode location.

**Evidence:** Some users questioned this when reading the start page and were unsure of what exactly was meant by ‘anywhere in Argleton City Centre’

**Comment by petegale** [comment]
![screen shot 2017-03-13 at 10 26 56](https://cloud.githubusercontent.com/assets/2970019/23850494/a57f848e-07d7-11e7-965e-edf5e4887c06.png)

**Comment by ingasiler** [comment]
Users need to know where their permit would allow them to park #239

**Comment by lizziebruce** [comment]
See #313

**Comment by petegale** [comment]
Leaving this issue open for now. Round 3 showed little evidence of this issue, however, responses on this page were dominated by the HMO copy, which may have obscured this issue

**Comment by lizziebruce** [comment]
Adding a screenshot of how the prototype for this page now looks. Now has the words:

> permit to park near your home 

in the first paragraph, and this screen comes after the postcode look up.

![screen shot 2017-05-22 at 11 59 36](https://cloud.githubusercontent.com/assets/27814324/26305290/967f299e-3ee6-11e7-9a92-3b5fd970c5d6.png)

**Comment by EUzkuraityte** [comment]
link to #259
