### ISSUE TITLE
Users need to know what GOV.UK Verify is so that they can make an informed choice

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#228]
**Impact:** Users will be more likely to make poor choices about application route.

**Evidence:** Some users raised questions about Verify at this point. What was it and what could it be used for?

**Comment by petegale** [comment]
![screen shot 2017-03-13 at 11 05 41](https://cloud.githubusercontent.com/assets/2970019/23851925/49f3bddc-07dd-11e7-842f-8e5dd075719a.png)

**Comment by suryanaga** [comment]
This is addressed in #240.
