### ISSUE TITLE
Users need to know why they need to prove their identity

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#229]
**Impact:** Without this, users struggle to understand the verification process.

**Evidence:** Some users questioned why their name, address and number plate wouldn’t be sufficient for a permit application.

**Comment by petegale** [comment]
![screen shot 2017-03-13 at 11 19 27](https://cloud.githubusercontent.com/assets/2970019/23852298/f963586c-07de-11e7-924c-299f577d2a37.png)

**Comment by petegale** [comment]
![screen shot 2017-03-13 at 11 20 15](https://cloud.githubusercontent.com/assets/2970019/23852321/0f728a42-07df-11e7-85a0-92c6aef02277.png)

**Comment by suryanaga** [comment]
This is addressed in #240.

**Comment by petegale** [comment]
![screen shot 2017-05-22 at 10 55 14](https://cloud.githubusercontent.com/assets/2970019/26303879/20ee6bb8-3ee1-11e7-917a-1db8e1bb561b.png)
