### ISSUE TITLE
ConTravel: Should we add libraries to photo options?

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#23]
From Herts:

"Within the example service, there’s an area where you upload your photo under the ‘I have a printed photo’ and then a link telling the user to ‘use a different service’.

Rather than default to paper, we could look into the possibility of libraries taking photos for users."

**Comment by joanneSouthern** [comment]
our contact centres take photos now for passes

**Comment by kateiw** [comment]
@sanjaypoyzer The other options here are council specific - so perhaps they shouldn't be included in the pattern?

**Comment by kateiw** [comment]
We want to find out how many councils actually do this, and if it occurs commonly enough to be included into the pattern.

**Comment by suryanaga** [comment]
Closing this as I feel it's basically an offline service.
