### ISSUE TITLE
Users clicked on the VISA logo on the payment screen before they entered their card number.

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#233]
**Impact:** Interacting with nonfunctional page elements will increase the perceived effort to complete the transaction.

**Comment by petegale** [comment]
![screen shot 2017-03-13 at 11 26 47](https://cloud.githubusercontent.com/assets/2970019/23852543/40413df2-07e0-11e7-9a19-d7ce8ba84b43.png)

**Comment by stephenjoe1** [comment]
This is something which has happened occasionally during Pay research but not to the extent that it has confused the user. The impact of trust that having the card symbols bring has outweighed the occasional user interaction with these symbols. It has also eliminated the occasions when users put in the wrong information in the card number box. Without the symbols some would start putting in their name for example.
