### ISSUE TITLE
Does white hair on white background get recognised by the face recogniser software? 

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#244]
This is a question for beta.

This seems to be an issue in the current passport service (as per [this tweet](https://twitter.com/eucalyptus44/status/841943391973842946)), and it could be more of an issue for older people more like to have white hair.

**Comment by anthonylord** [comment]
@sanjaypoyzer Is this a question for LAs or IDPs?

**Comment by suryanaga** [comment]
@anthonylord More for LAs, but would be great if IDPs are thinking about this too!

**Comment by petegale** [comment]
This is not a user research question
