### ISSUE TITLE
Some councils can't lookup boundaries by postcode entered

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#258]
Some councils can not lookup parking boundaries.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer @lizziebruce Do you think that this is something we should be looking to address or should we leave it for LAs to resolve? I think those LAs that can't do a  lookup should have a text version that explains where CPZs are in operation. Something like 'Check if you need a permit' section that details this information either in a short paragraph or a separate page if there's a lot that needs to be explained... What are your thoughts on this?

**Comment by suryanaga** [comment]
@EUzkuraityte We need to talk to the councils that have this issue and find out what information they can give, and in what format. From a technical perspective, if the information exists then it should just be a matter of getting it into the right format to then do a lookup.

**Comment by suryanaga** [comment]
Gonna close this as a duplicate / local issue on #259
