### ISSUE TITLE
Remove references to temporary permits

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#268]
At least one council (Ox) does not issue temporary permits, so there should be a local option to remove references to this.

**Comment by petegale** [comment]
Will add a configuration variable to councils.json for tempPermit= TRUE / FALSE and switch out temperorary permit messages based on that

**Comment by petegale** [comment]
BEFORE:
![start-before](https://cloud.githubusercontent.com/assets/2970019/24515068/56afd4d6-156e-11e7-90da-90065c60d53f.png)
![success-before](https://cloud.githubusercontent.com/assets/2970019/24515076/5b5a4a66-156e-11e7-864e-13929005e3bd.png)
AFTER:
![start-after](https://cloud.githubusercontent.com/assets/2970019/24515080/600dd51e-156e-11e7-92c6-ba439aad489c.png)
![success-after](https://cloud.githubusercontent.com/assets/2970019/24515095/6d658b30-156e-11e7-9519-9faca6897e42.png)
