### ISSUE TITLE
Some councils allow users to pick a permit up themselves from a council office

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#276]
Would be good to get some more detail about this from the councils that offer it.

**Comment by EUzkuraityte** [comment]
which councils offer this as an option?
confirm if this is actually faster?
what's the benefit as opposed to going to the office and making the application face to face?

**Comment by EUzkuraityte** [comment]
closing this as based on the LA responses none of the current pilot participants allow for this
