### ISSUE TITLE
Some councils will be integrating with Verify at LOA1 level

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#279]
The linked stable prototype should reflect this.

@EUzkuraityte Do you know which councils will be using which LOA?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer for PP only Cambridgeshire volunteered to use LOA1 (but others have until Thurs to express their interest)

**Comment by suryanaga** [comment]
- [x] Cambridgeshire, 
- [ ] Oxfordshire, 
- [x] Northumberland
- [x] Sunderland

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer please add Sunderland to the list. They just emailed us saying that they'd like to use LOA1
