### ISSUE TITLE
Users needed confirmation how they will be contacted on the application complete but the details of the contact methods don't reflect user's entered preferences

### ISSUE THREAD

**Issue by colin2678** [alphagov/verify-local-patterns#280]
the completed application page explains that you will not get a physical permit, but also asks for the user to display this in their car window. This should be one or the other

**Comment by petegale** [comment]
Hi @colin2678 I've taken a look and can't see the inconsistency. I might just be missing it. Could you be a bit more specific?

**Comment by colin2678** [comment]
Apologies, I have been away for the past couple of weeks. Please find attached a screen of the inconsistency.
![pp-application](https://cloud.githubusercontent.com/assets/26651509/25137476/c274b3c2-244f-11e7-9858-6b2cbd4040cd.PNG)

**Comment by colin2678** [comment]
^^ I hope that worked, as images are still blocked on Github for me :-(

**Comment by suryanaga** [comment]
Same as #280 but for parking permits

**Comment by EUzkuraityte** [comment]
I'm closing this issue as the new copy fixes it

![screen shot 2017-05-26 at 11 49 32](https://cloud.githubusercontent.com/assets/20285115/26491936/947aa47c-4209-11e7-93a0-068500be9353.png)
