### ISSUE TITLE
PP: Add 'any other information the user needs to provide' to start page list to include

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#29]
But only if the service is differing from the pattern (not recommended)

**Comment by suryanaga** [comment]
<img width="745" alt="screen shot 2017-01-10 at 10 42 04" src="https://cloud.githubusercontent.com/assets/4106955/21803328/7ca74a7e-d721-11e6-9fd9-e38157a25842.png">

To clarify, this is adding the words 'if the service differs from this pattern, include any other information the user needs to provide' to that list.

@kaydale - Cool to assign this to you?

**Comment by kaydale** [comment]
sounds good - as soon as I get my alpha gov account sorted :(
