### ISSUE TITLE
How do users respond to adding V5C information

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#292]
Some councils may require additional information to confirm ownership of the parked vehicle. If this takes the form of a scanned document, it has the potential to significantly degrade the user journey:
 - At present, one of the strongest motivators for choosing a verified pathway is avoiding the need to scan and upload documents. Including scanning and upload in the  verified transaction would reduce motivation to choose this route.
 - A significant number of users report they would be unable to scan and upload documents, and would abandon the process asked to do so.

This references issue #211

**Comment by EUzkuraityte** [comment]
Link to #264

**Comment by EUzkuraityte** [comment]
**Additional document upload - accepted proof**

Cambridgeshire County Council:
- Insurance documents

Northumberland County Council:
- V5C
- Insurance documents
- Company letter for company cars
- Car lease or rent agreement for rented or leased cars

   Oxfordshire County Council:
- V5C
- Company letter for company cars
- Car lease or rent agreement for rented or leased cars
- Sales invoice for new car in the past month; New registered keepers tear off slip; Old permit destroyed (if change of vehicle);

**Comment by EUzkuraityte** [comment]
![screen shot 2017-05-03 at 15 09 42](https://cloud.githubusercontent.com/assets/20285115/25664470/946bd770-3012-11e7-89a1-6d1af821d8b6.png)

**Comment by EUzkuraityte** [comment]
![screen shot 2017-05-03 at 15 11 50](https://cloud.githubusercontent.com/assets/20285115/25664566/ea07d436-3012-11e7-8022-c4c93a05e7f4.png)

**Comment by ingasiler** [comment]
![image](https://cloud.githubusercontent.com/assets/19390851/25743882/b848acf4-318e-11e7-9087-c4090bc075a5.png)

**Comment by ingasiler** [comment]
![image](https://cloud.githubusercontent.com/assets/19390851/25749584/f15e0b20-31a6-11e7-9670-88d08524164a.png)

**Comment by EUzkuraityte** [comment]
Closing this as we recommend not asking users to upload proof of vehicle docs or provide V5C info
