### ISSUE TITLE
start page and residents start page both mention when permits allow user to park

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#293]
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/start-page

Change this:
In some parts of Argleton, you'll need a parking permit to park your car or other vehicle.
Parking permits allow you to park within a given boundary, 24 hours a day and 7 days a week. - not needed as there's duplication between this page and residents parking permit page

To this:
You may need a parking permit to park your vehicle if you live in some parts of Argleton.

**Comment by suryanaga** [comment]
- This varies between councils.
 - This issue does not document a problem.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer I reworded it into an issue (see Title), either way I can see why we need to be repeating the same content on several pages of the prototype. Can this be looked into?

**Comment by suryanaga** [comment]
Ok, I've reworded it to be clearer.

Still not really sure why this is a problem though. It's on both those pages because the information would be useful at both parts of the journey.

**Comment by petegale** [comment]
In all our testing with users, we've seen that reading is often incomplete, and users forget what they've read as often as remembering it. As a principle, information should be available to the point of need. Requiring users to remember information they may or may not have read elsewhere is probably unwise.

also: https://www.nngroup.com/articles/recognition-and-recall/

**Comment by EUzkuraityte** [comment]
Ok, happy to close it now
