### ISSUE TITLE
User needs to know what different permits are available to them before the start of the transaction

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#294]
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/check-boundary

Change this:
To check if you need a permit, enter the postcode of the area where you'd like to park.

To this:
We would out if you or your visitors need a permit based on the the post code of the area where you live.

Enter your post code to find out:
- if you need a permit
- permits available to you

**Comment by suryanaga** [comment]
What problem does this solve?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer let's discuss. If LAs can make this info available then why not tell users not only if they need a permit, but also what kind of permit they can get.

The problem would be a user going through the whole Verify journey only to be told in the end that the household exceeded the max nr of permits allowed or that the address does not qualify for the permit they want.

**Comment by suryanaga** [comment]
Ah, I see, ok. Have reworded to be clearer.

**Comment by lizziebruce** [comment]
@EUzkuraityte @sanjaypoyzer 

A suggested quick fix is the below. 

![camden check permit screenshot](https://cloud.githubusercontent.com/assets/27814324/25273743/17bb3bb2-2685-11e7-97f6-be5f1542054b.png)

However I would like to know more context for this. It sounds like a resident's parking permit but we don't currently mention that. The breadcrumb trail suggests the user journey is from Park your car or vehicle directly to Check if you need a permit. Does this interaction attempt to simplify all permit queries with the postcode input routing users to more info and choices?  

I can see Camden currently offer:

Business and trade parking permits
Blue and green disabled permits
Residents' parking permits
Visitors’ parking permits
Other permits and parking

**Comment by suryanaga** [comment]
@lizziebruce Firstly, just a note that Camden aren't currently one of the Parking Permits service, but that's not a big issue.

So yeah, the idea behind the page is that it routes users to the right page no matter what their postcode is. However, there are more permits available to users as you mention that are not resident's parking permits, so the page should accommodate for that. I'll do a pull request with a go at this.

**Comment by lizziebruce** [comment]
@sanjaypoyzer Oh sure. I'll use Argleton as the one to edit going forward. 

In this case, it could be better for the content to say:

Before
"Check if you need a permit and if you are eligible to get one. ..."

After
"Check if you need a permit and if you're able to get one. ..."

The reason being that a) for some of the licences it isn't necessarily about eligibility, or it's a little odd to relate it to eligibility, for example if it's business parking only in an area then yes you're not exactly eligible if you but it's more that you can't apply for one. And b) I try to avoid using the word eligble whenever possible – though it is hard for services with eligibility criteria – as it isn't very plain English.

**Comment by lizziebruce** [comment]
@EUzkuraityte copy for content fix below. I'll put this into a pull request if everyone's happy. @sanjaypoyzer 

> # Check if you need a permit
>
> Tell us the postcode of the area you want to park in, to find out:
> 
> - if you need a permit
> - types of permit available to you
> 
> **Enter a postcode**
> For example SW1A 2AA
> [XXX XXX]

**Comment by EUzkuraityte** [comment]
@lizziebruce looks good, though should it be 'types of permits'? - though maybe not.. I'm not sure and will accept your current version if you think it's correct!

**Comment by lizziebruce** [comment]
@EUzkuraityte thanks. Countable nouns can be singular or plural after 'types of'. The wording flows better with singular in this example.

**Comment by lizziebruce** [comment]
@EUzkuraityte @sanjaypoyzer 
Understanding now that the [Journey start page](https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/start-page)  will route some users off to e.g. business and trade parking permits, I was about to open an issue with a similar title to this one.

Before
![screen shot 2017-05-09 at 11 38 18](https://cloud.githubusercontent.com/assets/27814324/25846980/07d32b3a-34ac-11e7-9f24-6cee117c595a.png)

After
I suggest we add this copy to make clear the different permits this page routes people to:

> For example, you might need a resident's parking permit, or a business and trade parking permit.

This may not have come up as an issue in UR as the recruited users were for resident's parking..

If I've misunderstood the holistic journey (again) please let me know. As mentioned at yesterday's stand up, it would be really useful for me to have a line sketch of the end to end journey with all the branches that would come off the prototype in real life. I think @EUzkuraityte offered to draw something up for @sanjaypoyzer to check? I also mentioned this in #488

Some branches I'd now except to come off the Start page:

-Resident's and visitor parking permits
-Business and trade parking permits

We should also signpost related services:

-Blue and green disabled permits
-Other permits and parking

**Comment by EUzkuraityte** [comment]
@lizziebruce @sanjaypoyzer your proposed copy looks good to me. I think Sanjay said it would take up  a lot of time and not really worth doing the sketch, but I'll give it a go at the end of the day! I think it would definitely help visualise the process

**Comment by lizziebruce** [comment]
@EUzkuraityte re #427 I would keep the copy on Check if you need a permit page as it now is i.e. 'the postcode of the area you want to park in' as this is the routing page – if they put in a trade address they will be given the option of a business and trade permit – right? 
Yes a sketch would be useful! I think you mentioned you would do it and ask Sanjay to check over it.

**Comment by petegale** [comment]
Re-opening until we can say from research that this is no longer an issue
