### ISSUE TITLE
User journey and content changes to 'you need a parking permit'

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#295]
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/resident-choice

Change this:

is within Argleton city centre, so you'll need a parking permit.

Are you a resident of Argleton city centre?

Are you a resident of Argleton city centre?

- Yes, I'm a resident 
- No, I'm a visitor

To this:
The post code [pull entered value from previous page] is within Argleton city centre, so you'll need a parking permit.

Argleton city centre residents can apply for resident and visitor permits.
Are you a resident of Argleton city centre?

- Yes, I'm a resident (route to the page that allows user select the number or type of permit they want to apply for, see #224 )
- No, I'm not a resident (route to alternative pages, not covered by this service pattern)

**Comment by suryanaga** [comment]
- The post code *does* get pulled from the previous page.
 - Suggested routing is not an issue, it's a solution to a problem. The issues you are talking about are already in #224 and #300.
