### ISSUE TITLE
PP: using consistent language throughout

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#298]
can we ensure that users always 'apply for a permit' not 'claim a permit'

**Comment by suryanaga** [comment]
@EUzkuraityte The reason it says "Claim your permit" on the page about choosing verify is to explain to users why they need to verify their identity. In other words they are claiming *their* permit rather than applying for *a* permit.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer I'm still not sure how the usage of the word 'claim' as opposed to 'apply' is conditional to choosing Verify, let's discuss at our meeting this pm

**Comment by lizziebruce** [comment]
@sanjaypoyzer @EUzkuraityte With the decision around 'claim'/ 'apply for' it's worth considering the entitlement psychology that @petegale was finding in UR, i.e. that people are more inclined to spend time verifying themselves if they feel grateful for the benefit they'll get from the end result and less inclined when they feel entitled to the thing. 
For (residential) parking permits this would vary locally, as for example in London a residential parking permit is gold dust whereas in a rural area it could be seen as an outrage i.e. an extra cost versus free street parking.
If we are to make a blanket choice, I'd add that 'apply for' is slightly more plain English than 'claim', i.e. it's more likely to be understood by a larger number of users.

**Comment by suryanaga** [comment]
Closing this as it doesn't say "claim your permit" anymore
