### ISSUE TITLE
Both: Add checkbox about consenting to use data from Verify on start pages

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#3]

**Comment by suryanaga** [comment]
Going to check with Ant Lord about this, but possibly we should be following the pattern used [here](https://claim.redundancy-payments.service.gov.uk/claims/choose-how-to-verify)

In particular, I'm unsure whether or not we should take out any mention of Verify from the start page as in the redundancy service.

**Comment by irinapencheva** [comment]
Could we make sure that whatever we agree to is also replicated in the Blue Badge pattern?

**Comment by suryanaga** [comment]
@irinapencheva Yeah, that makes sense. We should talk about when/if we're going to include the Blue Badge pattern in this project.

**Comment by suryanaga** [comment]
Reopening this issue as it's not done on both services.

**Comment by kaydale** [comment]
@sanjaypoyzer this isn't done for con.travel... did you want me to do it, or was that the test?

**Comment by suryanaga** [comment]
@kaydale Did you check out the right branch that PR #48 has?

**Comment by kaydale** [comment]
@sanjaypoyzer in sourcetree Im on branch "move-verify-stuff" and in local host I can not see that this 
![Uploading Screen Shot 2017-01-13 at 14.45.52.png…]()

**Comment by kaydale** [comment]
Im on sourcetree now and I checked out branch move-verify-stuff but I see this when I go to localhost.
![screen shot 2017-01-13 at 14 45 52](https://cloud.githubusercontent.com/assets/20561170/21933911/4459c342-d99f-11e6-887d-1194f19996c8.png)
which is why I am not sure whats going on

**Comment by suryanaga** [comment]
Check the branch on #48 again ;)

**Comment by kaydale** [comment]
So you made a new branch (move-verify-stuff-2) so I checked it out and now on local host I see 
![screen shot 2017-01-13 at 15 02 09](https://cloud.githubusercontent.com/assets/20561170/21934463/63b25856-d9a1-11e6-9bed-028ac7655de9.png)

Meaning I think this issue is now fixed :)
