### ISSUE TITLE
Users need to understand that you can't use a paper photo

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#301]
If you answer that you already have a paper photo, you never get the option to use a tablet or a smartphone to take a picture.

**Comment by suryanaga** [comment]
Adding this flowchart here illustrating the current flow:

<img width="903" alt="screen shot 2017-04-12 at 12 35 29" src="https://cloud.githubusercontent.com/assets/4106955/24955740/a0eb0008-1f7c-11e7-8945-b02d22147979.png">

The flowchart shows that you can not get to the Take photo with your device page if you answer "Yes" to the first question. 

This is not intended!

**Comment by suryanaga** [comment]
Going to change it to the routing illustrated here:

<img width="875" alt="screen shot 2017-04-12 at 12 49 10" src="https://cloud.githubusercontent.com/assets/4106955/24956207/81f14b56-1f7e-11e7-8838-e4e0844c27c2.png">

**Comment by petegale** [comment]
Waiting for evidence from research before closing

**Comment by suryanaga** [comment]
@tracyeaton Hi Tracy, could you expand on what you've seen about users getting confused by the word 'digital'? We've added that word so that users know they can't use a paper photo. (cc @lizziebruce)

**Comment by TracyEaton** [comment]
@sanjaypoyzer Hi Sanjay, it came up recently when we asked if they had a digital camera and the answer was no, but they did have a smart phone. I just thought that the word digital was confusing to some people, they may have a perfectly good photo on their phone they could use but do not consider it a digital picture.

**Comment by suryanaga** [comment]
Ah ok, in that case, that is more about issue #202 - Users need to know they can use a mobile phone. 

We've addressed that issue recently in the changes made in Pull Request #245, and will be looking to see if it's fixed in the next round of testing.

**Comment by petegale** [comment]
Limited evidence (2 users) in round 3 suggests that this may be addressed. Leaving open until we have more conclusive evidence
