### ISSUE TITLE
Service pattern content changes

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#302]
A number of small changes required to the wording of the service pattern. All are outlined in this document:
https://docs.google.com/document/d/1SK3oFzYGLWwTRxj93QHAiwONG3n_ZLmSWonlxzFibWg/edit#

**Comment by suryanaga** [comment]
Please submit those issues as seperate ones. This way of submitting issues completely breaks our current way of working.

**Comment by irinapencheva** [comment]
@samuelculley - could you help with resubmitting these wording changes as separate issues to comply with the above?
