### ISSUE TITLE
Should we reword upload of photograph instruction on start page?

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#304]
On "You'll upload a digital photo as part of the application.' 

Isn't the process also about 'taking' a photo so should be reworded?

**Comment by suryanaga** [comment]
@irinapencheva Can you explain what the issue here is? What do you think is the intended result of leaving it how it is?

**Comment by irinapencheva** [comment]
@sanjaypoyzer - if I read this, I'd assume / understand it as the act of uploading a picture from a camera on my computer and would assume there's no way to take a picture as part of the application (i.e. if I have a webcam/ tablet).

We could park this item in 'Icebox' for the content designer's review?

**Comment by suryanaga** [comment]
@irinapencheva Yeah, I'm not really sure that's a real issue. It's not something we've seen in user research, and you (and I) have got too much contextual knowledge of the process to know what our genuine reaction to the content would actually be.

**Comment by lizziebruce** [comment]
Coming to the content afresh, as a user I'd assume I needed to have one already. 
As the photo has to meet set criteria it could cause frustration if a user went to the trouble of taking a new photo (and possibly also transferring to device) and then found out later in the journey it was unsuitable. 

We could amend the 'About your application' section to the following – but it becomes a bit copy-heavy... 

> <img width="515" alt="screen shot 2017-04-28 at 17 54 56" src="https://cloud.githubusercontent.com/assets/27814324/25538751/d7898f14-2c3b-11e7-97b6-65106085ecfc.png">

On the other hand, saying, for example, "You can take a photo during your application" raises more questions than it answers.

Perhaps we should put this in the Icebox and see if users find it an issue?

**Comment by irinapencheva** [comment]
Thanks @lizziebruce I'll close it now as it's linked to #303
