### ISSUE TITLE
Incentives for choosing the Verify Option

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#306]
User research should check if the updated incentives for choosing the Verify option are more appealing? What do people choose? Does the way the options are written make sense to users? Do they know why they go through Verify for this service?

**Comment by petegale** [comment]
This is covered by #45, and it's definitely on our list of research questions

**Comment by irinapencheva** [comment]
Great, if these ?s are still applicable for the updated prototype, will close this issue

**Comment by suryanaga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Is putting Verify in front of the application process going to cause higher dropout?](https://trello.com/c/kCO0ohKk/14-is-putting-verify-in-front-of-the-application-process-going-to-cause-higher-dropout)
