### ISSUE TITLE
Confirm your address - do users read and choose correct address?

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#310]
User research to check if this is not current address do users actually read the address that's returned from Verify? Do they have problem with entering a new address?

**Comment by petegale** [comment]
User research (concessionary travel r2) shows that **most** people notice this, but also that they object to re-keying address data.

**Comment by irinapencheva** [comment]
@petegale do you think the latter part of this finding should be transformed into a new issue?

**Comment by petegale** [comment]
Yes

**Comment by irinapencheva** [comment]
Evidence form latest round of user research on Concessionary travel:
![screen shot 2017-06-14 at 14 54 22](https://user-images.githubusercontent.com/24913176/27135802-71cdaf70-5111-11e7-87c3-fc4747337169.png)
