### ISSUE TITLE
Your bus pass photo - You can't select "I'm not sure" as an option

### ISSUE THREAD

**Issue by ghost** [alphagov/verify-local-patterns#312]

**Comment by suryanaga** [comment]
@samuelculley Which page? The one which asks "Do you have a photo?"

**Comment by irinapencheva** [comment]
![screen shot 2017-04-21 at 10 04 25](https://cloud.githubusercontent.com/assets/24913176/25270861/fa46325e-2679-11e7-8637-662330b1cb53.png)
@sanjaypoyzer - this refers to the screen above

**Comment by suryanaga** [comment]
Ah ok cool.
