### ISSUE TITLE
Users needed confirmation how they will be contacted on the application complete but the details of the contact methods don't reflect user's entered preferences

### ISSUE THREAD

**Issue by ghost** [alphagov/verify-local-patterns#319]
This section should depend on what information has been provided - if the user hasn't provided an email address, then no confirmation could be sent at this point.

**Comment by petegale** [comment]
I think that is the intention here. It may be a bug.

**Comment by suryanaga** [comment]
@samuelculley Can you say exactly what you did and what you saw?

**Comment by irinapencheva** [comment]
On the "Application complete' page it always says "you will receive an email and text" (see below), irregardless of what options you've selected for your confirmation messages

![screen shot 2017-04-21 at 10 15 50](https://cloud.githubusercontent.com/assets/24913176/25271327/afda2f48-267b-11e7-9c8d-e75d63b48684.png)

**Comment by irinapencheva** [comment]
@sanjaypoyzer - can we remove the 'needs clarification' label as well or is it still unclear?

**Comment by irinapencheva** [comment]
@sanjaypoyzer - did you say this issue is now resolved?

**Comment by suryanaga** [comment]
@irinapencheva nope, haven't worked on this yet
