### ISSUE TITLE
Question - do we need two prototype pages when it can be done in one?

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#320]
Info on these two pages:

- https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/prove-identity
- https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/pre-verify

could potentially be summarised in one. Issue being that we should not force users through extra steps and prototype screens unless we absolutely have to. 

For an example see this:

![screen shot 2017-04-11 at 13 53 43](https://cloud.githubusercontent.com/assets/20285115/24910296/328c2b2c-1ebf-11e7-8355-0a49aebd041a.png)

**Comment by petegale** [comment]
I disagree with the premise that these pages should be combined and this contradicts some of our core design principles. Specifically: https://www.gov.uk/service-manual/design/form-structure#start-with-one-thing-per-page.

Perhaps this could be re-phrased as a question about whether users are experiencing problems relating to these being two separate pages

**Comment by EUzkuraityte** [comment]
@petegale would you be able to explain what is a 'thing' in this context? 

The way I see it, we're presenting the options to the user on how he/she can apply for a permit. And this is the one 'thing' that the Redundancy payment screen does. But please let me know if this is not the case.

@sanjaypoyzer maybe we could also link us to the service designers who assessed the service to find out the basis for their decision to have a screen like this?

Finally, more than happy to put both versions in front of users to test and see to which version is easier to use.

**Comment by suryanaga** [comment]
@EUzkuraityte We used to have a page that looked like that. It tested really badly. Documented in #240.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer  there's new evidence from Northumberland see #355 

something like 6 or 6b in [your doc](https://docs.google.com/presentation/d/1xL9vh3SoXQ5LoAheqdSlYQDB_wNgCvCrsHUnzFQzlAo/edit#slide=id.g21153d824a_0_122) would make sure user's journey is a little shorter..

Can we test with two versions? i.e. the current one and 6 or 6b

One of the issues that came out of user research is that people with less digital confidence also struggle with clicking on things (see #350 and #390), so making them do it several times on three pages instead of twice on a single page should be avoided.

**Comment by sanjaypoyzer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can iPad / non-mouse users use the service without assistance?](https://trello.com/c/xTlU7rN1/3-can-ipad-non-mouse-users-use-the-service-without-assistance)

**Comment by sanjaypoyzer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Can iPad / non-mouse users use the service without assistance?](https://trello.com/c/xTlU7rN1/3-can-ipad-non-mouse-users-use-the-service-without-assistance)

**Comment by suryanaga** [comment]
Disagree that those versions are clearer. These pages work well now for all users we've tested with and there's no clear problem to solve by combining them.

**Comment by EUzkuraityte** [comment]
![screen shot 2017-06-16 at 15 52 59](https://user-images.githubusercontent.com/20285115/27231860-ef2f3be6-52ab-11e7-847d-39047c04fe88.png)

Evidence from Cambridgeshire

**Comment by suryanaga** [comment]
@EUzkuraityte That page is from a different part of the journey then the one this issue talks about

**Comment by EUzkuraityte** [comment]
Nicely spotted @sanjaypoyzer ! I'm keen to keep this as closed anyway as we've not seen this to cause issues to any users in terms of getting through the application. Let me know if you'd prefer to open it
