### ISSUE TITLE
Users need to know in advance about personal information they would need to provide in the Verify process

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#322]
![issue1](https://cloud.githubusercontent.com/assets/27288208/24912737/eee75fba-1ec6-11e7-8e99-c164b1491f40.PNG)

**Comment by EUzkuraityte** [comment]
I remember this not being an issue for LOA1 journeys

**Comment by lizziebruce** [comment]
@EUzkuraityte can I unassign myself as the recent content changes will hopefully be sufficient to resolve this user need. If we still see it I can be re-assigned. thanks

**Comment by EUzkuraityte** [comment]
@lizziebruce yes, of course!

**Comment by petegale** [comment]
Round 3 suggests we've met this need:
![screen shot 2017-05-22 at 10 55 14](https://cloud.githubusercontent.com/assets/2970019/26302740/27a44ea4-3edd-11e7-9481-fb546afd7f62.png)
