### ISSUE TITLE
Users need to know when their application is complete

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#327]
![issue6](https://cloud.githubusercontent.com/assets/27288208/24913187/44b0c340-1ec8-11e7-8fa8-4d8b45f0e356.PNG)

**Comment by suryanaga** [comment]
Suggest that Sunderland fix the styling of the success page and test again to see if the issue persists.

**Comment by EUzkuraityte** [comment]
@GWSunderland have you managed to look at styling at all? Is this still an issue?

**Comment by GWSunderland** [comment]
@EUzkuraityte We've now resolved this issue in our local prototype

**Comment by suryanaga** [comment]
@GWSunderland Have you submitted your local prototype updates back as a pull request?

**Comment by GWSunderland** [comment]
@sanjaypoyzer We'll get this sorted out

**Comment by EUzkuraityte** [comment]
Closing this as I believe this particular error was fixed
