### ISSUE TITLE
Should the prototype/pattern include choice of permit?

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#33]
What are the choices of permit that different councils have?

**Comment by kaydale** [comment]
@sanjaypoyzer For Sunderland they have different permits for different areas of the town. Some are free permits some are chargeable. 

The other scenario might be resident permit vs visitor permit.

**Comment by suryanaga** [comment]
@kaydale Yep, area of permit should definitely be one.

Visitor permit is out of scope for the pilot, but we should add a fake link to a resident's permit service in there.

**Comment by kaydale** [comment]
Pete adds:
Some councils have parking zones (not sure if costs vary between zones), so we may well need to be able to support the idea that you might be applying for a permit for Argleton Zone X, or possibly for Imaginary Hill in Argleton
https://www.canterbury.gov.uk/parking-travel-roads/apply-for-a-parking-permit/
https://www.brighton-hove.gov.uk/content/parking-and-travel/parking/resident-parking-permit

**Comment by joanneSouthern** [comment]
we issue a visitor permit and an allocated to a car permit per household, i wouldnt want to have to separate processes  for the pilot as they will run out at the same time and thus they apply for them both at the same time, we can probably handle this within the form

**Comment by suryanaga** [comment]
So I'm thinking that I'll add a page in the example service where people can also apply for a visitor's permit at the same time by checking a box. Would this satisfy this issue do you think @kaydale @EUzkuraityte ?

**Comment by petegale** [comment]
This isn't a user research question, but a design decision. Once we make that decision we can then understand the impact of that decision through research.

**Comment by suryanaga** [comment]
We have it down as an issue in #224, and so I will build it as a thing, but I think we need do some research to find out whether or not this is actually a thing people need to do

**Comment by petegale** [comment]
We know there is a need to apply for residents and visitors permits at the same time. We also know that where permit limits allow it (especially with visitors scratch cards) there is a need to buy more than one at a time. 

Text file attached contains all the variation in permit type and zone for participating councils
[permit types.txt](https://github.com/alphagov/verify-local-patterns/files/903263/permit.types.txt)

**Comment by suryanaga** [comment]
Ok closing this then as it's an answered question.
