### ISSUE TITLE
Users need to know that they will need their vehicle registration number

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#332]
![issue11](https://cloud.githubusercontent.com/assets/27288208/24913666/be802f70-1ec9-11e7-9d78-3509c58daac2.PNG)

**Comment by lizziebruce** [comment]
@EUzkuraityte I suggest things that users will need to complete applications/transactions are listed out on first page of user journey. Similar issues #348 #356

**Comment by lizziebruce** [comment]
We could add:

> You’ll need:
> 
> - documents to prove you live in Argleton city centre
> - car registration number
> - V5C registration document
> - to answer security questions or upload identity documents

Might be worth considering a box in a consistent place on all local service applications Start pages, which would list out what you'll need. Something like:

<img width="298" alt="screen shot 2017-04-28 at 18 51 45" src="https://cloud.githubusercontent.com/assets/27814324/25540648/c6984436-2c43-11e7-8c03-5344af9ceec0.png">

**Comment by lizziebruce** [comment]
@EUzkuraityte @sanjaypoyzer if people are happy with the content suggestions above I'll make this a pull request. Sanjay, what do you think about the box idea?

**Comment by EUzkuraityte** [comment]
@lizziebruce happy to try this out! the only thing would be is take off V5C reference, as the common prototype will not require users to prove their link to the car.

**Comment by lizziebruce** [comment]
@EUzkuraityte @sanjaypoyzer can we do the IF rule here? So that **if** the council **does** require V5C then this **will show** in the docs required list? As user need was to know everything they needed upfront.

**Comment by suryanaga** [comment]
@lizziebruce Yes, we'll only show the reference to V5C if it's a council that requires it.

Re: The box - Things like that can get over-used really quickly, so best to keep them out if at all possible. In any case, this issue is about users need to know that they'll need their registration number. Let's add that to the list of things they need on the start page, and work out how to make sure users read that list as part of a separate issue.

**Comment by lizziebruce** [comment]
@sanjaypoyzer so I'll put this in a pull request – and ask you to add the rule around shows IF... for V5C.

> You’ll need:
> 
> - documents to prove you live in Argleton city centre
> - car registration number
> - V5C registration document
> - to answer security questions or upload identity documents

**Comment by lizziebruce** [comment]
See also copy rescope for Start page in #313 with related PR #512

**Comment by petegale** [comment]
No evidence of this issue in Round 3
