### ISSUE TITLE
Need a verify prototype instance to support address change

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#335]
This is linked to #310

**Comment by irinapencheva** [comment]
@EUzkuraityte - do you  mind if we move this item from the CT column as a top priority for PP as it impacts your service a lot more? 
@sanjaypoyzer - looping you for visibility

**Comment by EUzkuraityte** [comment]
@irinapencheva sure!

**Comment by suryanaga** [comment]
@irinapencheva @EUzkuraityte I think it's best to have 2 seperate linked issues, one for PP and one for CT. That should reduce confusion when talking about priorities.

**Comment by irinapencheva** [comment]
great, thanks! I'll move it down the priority list then

**Comment by suryanaga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confirm your address - do users read and choose correct address?](https://trello.com/c/CFzLP9Dt/4-confirm-your-address-do-users-read-and-choose-correct-address)

**Comment by suryanaga** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Confirm your address - do users read and choose correct address?](https://trello.com/c/CFzLP9Dt/4-confirm-your-address-do-users-read-and-choose-correct-address)
