### ISSUE TITLE
Users needed to upload a photo, but couldn't do so without assistance

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#347]

**Comment by irinapencheva** [comment]
#468

**Comment by suryanaga** [comment]
I'm going to find a place for some guidance which helps users through the process of uploading, kind of like the guidance for [connecting to GovWifi](https://www.gov.uk/government/collections/connect-to-govwifi). (ie With screenshots for the various operating systems a user could be using.)

**Comment by suryanaga** [comment]
So I'm thinking something like this:

![screenshot-localhost-3000 2017-04-28 15-03-10](https://cloud.githubusercontent.com/assets/4106955/25532073/d99a68fe-2c23-11e7-8718-623390e84eb1.png)

It'll need a different image for Windows, ChromeOS, Android, and iOS users (and possibly slightly different text?), but we can fairly reliably use the browser's user agent to work out which image to display. We should add a link in there to change the image to a different OS if needed though

That's all assuming the image is needed. We generally advise against using images, but I think in this case it might be needed in order to help the user through the task.

Thoughts? @lizziebruce @petegale

**Comment by lizziebruce** [comment]
@sanjaypoyzer @irinapencheva agree an image is useful in this context. Would advise the screenshot reflects generic folders a user would have i.e. shows just Downloads and Pictures under Documents (and no VerifyLocal folder).

**Comment by lizziebruce** [comment]
@sanjaypoyzer also, if it's an issue for users, we could amend the second instruction copy to:

> Double click on your file, MyPhoto.jpg in the example above, to select it.

And perhaps lose the word digital from the first instruction copy as it would flow better. (If anything, digital could be added in front of photo on the non-drop down content.)

**Comment by irinapencheva** [comment]
Results from latest user research 
![screen shot 2017-06-14 at 16 17 15](https://user-images.githubusercontent.com/24913176/27140242-f99e4efe-511c-11e7-8b68-d85fb041afc5.png)

@lizziebruce - do you think a small content fix can address this?

**Comment by lizziebruce** [comment]
@irinapencheva @petegale I'm not sure how much more we can help users with this. It's more an issue of lack of digital competence. We could spell it out more in the bullets:

<img width="501" alt="screen shot 2017-06-29 at 16 40 25" src="https://user-images.githubusercontent.com/27814324/27696516-b95f68ae-5ce9-11e7-8c91-27642c29a32d.png">

However, it seems like 
a. users were all focusing on the email option 
b. users who were confused didn't click on the Get help transferring photo link

So perhaps we could move the help content about email up onto the main part of the page, and make the link into 'Other ways to move your photo onto your computer'. For example:

<img width="663" alt="screen shot 2017-06-29 at 17 09 44" src="https://user-images.githubusercontent.com/27814324/27698032-d28ee72e-5ced-11e7-8991-168a28476495.png">

<img width="619" alt="screen shot 2017-06-29 at 17 09 54" src="https://user-images.githubusercontent.com/27814324/27698042-d9e7a6fa-5ced-11e7-9b3f-16116c0b1d3c.png">

**Comment by irinapencheva** [comment]
@lizziebruce - this approach seems good. @petegale - do you think we saw enough users to assume email is preferred as the primary route for file transfer to implement this change?

**Comment by irinapencheva** [comment]
@petegale - any guidance or views as per above?

**Comment by petegale** [comment]
From what I've seen in our testing, and heard from the work done on this for passports, I think it's safe to say that email is the most likely option.

However, I'm not sure we need to go so far with the explanation. What they found on 'passports' was that once someone gets the concept of emailing it to themselves, most can do so. 

I think the simplest option above is probably the best, just say "Email the photo to yourself and download it to your computer"

Reviewing the issues from UR in a little more detail:

**People thought they had to email it to the council:** I've got a feeling that the title of this page "Transfer your photo to this computer" may reinforce the perception of having to email the photo to the council.
**Security concerns:** It may also be that the big green button saying 'my photo is now in this computer' adds to these concerns. One might think that by clicking that, I'm giving access to files on my computer.

**Comment by lizziebruce** [comment]
Thanks @petegale . So, keep the explanation of emailing to self in the expandable section, and changing the title and green button copy. @sanjaypoyzer just to loop you in on this.

**Comment by petegale** [comment]
@lizziebruce that seems to make sense, if we can come up with something better for the title and button.

**Comment by lizziebruce** [comment]
Content solution – updated on prototype:

![screen shot 2017-07-19 at 17 25 45](https://user-images.githubusercontent.com/27814324/28378370-d6109e78-6ca7-11e7-9df7-97f6a1e46a36.png)

![screen shot 2017-07-19 at 17 22 16](https://user-images.githubusercontent.com/27814324/28378375-dd14251e-6ca7-11e7-9585-3bfcfc425e1b.png)

**Comment by irinapencheva** [comment]
That is very clear to me! Thanks for the super quick action Lizzie
