### ISSUE TITLE
Users were unable to take a selfie and upload this onto their computers

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#349]

**Comment by suryanaga** [comment]
@joanneSouthern Could you provide some more information about this please? Perhaps paste in a screenshot of the slide deck you showed to us the other day?

**Comment by joanneSouthern** [comment]
@sanjaypoyzer  they said they wouldnt be able to do it without assistance

**Comment by suryanaga** [comment]
@joanneSouthern What screen were they looking at when they said this?

**Comment by joanneSouthern** [comment]
the screen where it asks you if you have a photo on your computer

**Comment by suryanaga** [comment]
@joanneSouthern So they answered "Yes" to "Do you have a photo like this?", then got asked "Is your photo on this computer?" and then said they'd ask for assistance at that point?

**Comment by joanneSouthern** [comment]
yes @sanjaypoyzer , they said it was in the drawer in their house, we asked was it a printed out photo they said yes done in either a booth or by a professional photographer, often left over from when they applied for their passports

**Comment by suryanaga** [comment]
Ah, ok so this is related to #301 possibly.

Did the user not feel confident in clicking "No" to answer the question at this stage then? I'd expect users to be able to answer that question fine so I'm a little confused why they would drop off at this stage.

**Comment by joanneSouthern** [comment]
I believe the question says 'do you have a photo like this'
it doesnt say at that point is it on your computer so they answer yes

**Comment by suryanaga** [comment]
@joanneSouthern Sure, so that's fine if they answer "yes" at that point, and then answer "no" on the question about it being on their computer. They'll still be routed to taking a new photo.

**Comment by irinapencheva** [comment]
@joanneSouthern - issue #301  and new UR issues, which Pete is adding will also address some of the content design issues. So I'll close that one and address in the other issues
