### ISSUE TITLE
users didnt realise they were finished

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#352]

**Comment by suryanaga** [comment]
I think this could be an issue with the current styles on Northumberland's prototype.

**Comment by petegale** [comment]
@sanjaypoyzer It's worth noting that this issue has also been reported by Bucks and Sunderland as well as in round 1 of parking permits for Argleton. So it may not just be styling.

**Comment by suryanaga** [comment]
@petegale Ok, I'm going to do some organising of all the issues related to this page because there's a few now...

**Comment by suryanaga** [comment]
OK, so #237 is the related issue for Parking Permits. As per other issues, we'll keep both around. That issue now also references #327 and #385, although both of those issues have local issues that could do with being addressed.

@petegale Are there any other versions of this issue that I've missed? Have the Bucks issues made it onto github yet?

**Comment by petegale** [comment]
@sanjaypoyzer not that I'm aware of. @samuelculley should be doing the Bucks issues today or tomorrow

**Comment by irinapencheva** [comment]
@sanjaypoyzer - this is also an issue for Bucks #425

**Comment by suryanaga** [comment]
Duplicate of #237
