### ISSUE TITLE
Users need to know how much their permit will cost before they start the application

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#356]

**Comment by lizziebruce** [comment]
@EUzkuraityte I suggest things that users will need to complete applications/transactions are listed out on first page of user journey. Similar issues #348 #332

**Comment by lizziebruce** [comment]
New copy with more detail:

> A resident's parking permit costs £51 for 12 months and £25.50 for 6 months.

https://docs.google.com/document/d/1b9rLsp0rQF199U4JLsZtNezuQR9kCI_U-hkHl6E3N6w/edit#heading=h.r96wk8rljsr7

**Comment by lizziebruce** [comment]
@EUzkuraityte @sanjaypoyzer will create a pull request with new copy above ^^^

**Comment by petegale** [comment]
No evidence of this issue in Round 3
