### ISSUE TITLE
costs are incorrect

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#357]

**Comment by EUzkuraityte** [comment]
Hi @joanneSouthern is this a local issue or the common prototype?

Hi @sanjaypoyzer I assume that LAs should be able to display the permit price set by their council in their prototype. Is that correct?

**Comment by lizziebruce** [comment]
See #313

**Comment by lizziebruce** [comment]
Believe this is a duplicate of 313 and should be closed – @sanjaypoyzer do you agree?

**Comment by suryanaga** [comment]
@EUzkuraityte Yes councils can set the costs by submitting a pull request.
