### ISSUE TITLE
PP: What should a user do if they lose their permit?

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#36]
Should probably add some content onto the start page (Section 3) and also the section about renewals (Section 8)

Also worth putting a thing in Section 3 when we talk about renewals that says something like "To read more about renewals, scroll down to Section 8"

**Comment by kaydale** [comment]
This is the same as #62 so I will delete this one

**Comment by suryanaga** [comment]
@kaydale #62 is marked ConTravel, where as this is PP (parking permits).
