### ISSUE TITLE
Users need to know that they can't get verified early in the journey

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#366]
Northumberland PP - over 20 and lived in UK - Users said that this information should have been listed on the first apply page. Getting to this point in the process then finding you can’t apply via this route might be frustrating to Users need to know that they can't get verified early in the journey

**Comment by suryanaga** [comment]
Living in the UK isn't an issue as it's for a resident's parking permit in the UK.

The Over 20 thing does not apply for LOA1 (it currently still shows in the LOA1 prototype, but that's an error), so this only applies for those councils which are using LOA2.

For those councils who need LOA2, users who are **unlikely to Verify** (doesn't mean they definitely can't) will be routed back to the council from Verify once they answer that question in the Verify 'hub'. 

This screenshot shows this page as current in the Check Your State Pension service:

![screenshot-www signin service gov uk 2017-05-17 12-52-46](https://cloud.githubusercontent.com/assets/4106955/26152684/dc74325e-3aff-11e7-811c-176d6351ed12.png)


Of course finding out a little bit earlier in the journey would be preferable, but it would require additional content which would be unnecessary content and repetition for the majority of users. So in the spirit of making something that works as well as possible for everyone, I'm not sure it's an improvement that we should make. 

@EUzkuraityte @petegale To confirm closing this issue?
