### ISSUE TITLE
PP: Add requirement for expiry date on temporary permit

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#37]
When talking about temporary physical permits, we should mention that they need to clearly display the expiry date

**Comment by kateiw** [comment]
@sanjaypoyzer is this telling users to clearly display the expiry date? or telling councils the expiry date should be clearly visible so users can see and are reminded when it expires?

**Comment by kateiw** [comment]
@sanjaypoyzer ie clearly visible to who?

**Comment by suryanaga** [comment]
@kateiw It concerns the design of the actual permit. In other words, the permit must clearly show the expiry date so that it is clearly visible to wardens who are checking it. Not 100% sure where this should go - Probably in Section 9: Checking permits.
