### ISSUE TITLE
Choice between a 6 month or 12 month permit

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#375]

**Comment by EUzkuraityte** [comment]
Northumberland PP - Users were confused with the choice of a 6 month and 12 month choice with no obvious benefit (e.g. reduced price for 12 months)

Bucks PP - Expressed happiness that permits will be available for 6 months (change of ownership) 

on this page: 
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/resident-start

**Comment by colin2678** [comment]
This was due to Bucks not currently offering a refund for customers if they change house/cars. We plan  to do this in the future.

**Comment by joanneSouthern** [comment]
we only offer a 12 month option

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer can you let us know - can LAs choose whether to give a user the option between 6 and 12 months, or not? 

I though this could be localised..

**Comment by suryanaga** [comment]
@EUzkuraityte Yes, this can be localised. Councils were supposed to submit pull requests with their local settings on the prototype, but I'll just do it now.
