### ISSUE TITLE
Users need a better way to enter dates

### ISSUE THREAD

**Issue by joanneSouthern** [alphagov/verify-local-patterns#376]
Users felt the layout of this page was poor with boxes too close together.   Users felt a calendar popup to choose a date would be helpful

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer please could you advise the reasoning behind boxes vs calendar and in our current date entry display and if the box sizes meet accessibility requirements.

**Comment by EUzkuraityte** [comment]
Closing as this is a duplicate of #409
