### ISSUE TITLE
ConTravel: Add to start page a comment that the service is for age-based concessionary travel and not disabled passes

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#38]

**Comment by kateiw** [comment]
@irinapencheva did this come from user research? I would avoid adding this comment unless we know people are confused by the information already provided. It's already very clear it's for older persons from the title.

**Comment by irinapencheva** [comment]
@kateiw  I think a council had a comment, but you're right - it's clear from the title.
