### ISSUE TITLE
Can iPad / non-mouse users use the service without assistance?

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#390]

**Comment by irinapencheva** [comment]
Latest round of user research suggests iPad users can largely use the service without assistance. The following minor issues were encountered, which can be addressed in Beta

![screen shot 2017-06-14 at 16 13 23](https://user-images.githubusercontent.com/24913176/27140080-8f7c6768-511c-11e7-97e7-94e227485638.png)

![screen shot 2017-06-14 at 16 14 53](https://user-images.githubusercontent.com/24913176/27140113-a2002622-511c-11e7-954b-27a8fc30b81e.png)
