### ISSUE TITLE
Users need to know what GOV.UK Verify is

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#400]
![image](https://cloud.githubusercontent.com/assets/20285115/25168686/64154a02-24dc-11e7-8148-2bae521fa691.png)

**Comment by ingasiler** [comment]
Link to #410

**Comment by petegale** [comment]
Round 3 suggests this problem has been addressed:
![screen shot 2017-05-22 at 10 46 03](https://cloud.githubusercontent.com/assets/2970019/26302370/e507f164-3edb-11e7-9f5c-5d6c19917255.png)
