### ISSUE TITLE
Users need to know they can use GOV.UK Verify whether or not they already have an account

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#401]
'I do not think I am registered with GOV.UK'

![image](https://cloud.githubusercontent.com/assets/20285115/25168790/b6ac887a-24dc-11e7-9deb-460522a2b12f.png)

'User assumed they already had a Verify account on this page'

![image](https://cloud.githubusercontent.com/assets/20285115/25168838/f081f27e-24dc-11e7-9a77-da906e8875fa.png)

**Comment by petegale** [comment]
Not seeing this issue in Round 3
