### ISSUE TITLE
Users need to know why councils can't use information that they already hold about them to verify their identity

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#403]
![image](https://cloud.githubusercontent.com/assets/20285115/25169013/70941e42-24dd-11e7-99a1-99deca109d01.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169018/73dee140-24dd-11e7-8338-5f56f6ea1f63.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169021/7689d300-24dd-11e7-871e-c123a0fbb7b8.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169026/79c4aa86-24dd-11e7-836a-684eb2899874.png)

**Comment by colin2678** [comment]
This is linked to issue #400. Users are unsure of what Verify does.

**Comment by EUzkuraityte** [comment]
Closing this via #400. The issue is no longer observed in user research.
