### ISSUE TITLE
User thought a photograph could be used to verify

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#404]
![image](https://cloud.githubusercontent.com/assets/20285115/25169096/b9422efe-24dd-11e7-8cee-41093fa9fa1b.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169104/be7ff478-24dd-11e7-99b4-245018fe4deb.png)

**Comment by suryanaga** [comment]
Closing this as it doesn't seem like an issue or explain what went wrong
