### ISSUE TITLE
Low percentage of users are able to install apps

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#405]
![image](https://cloud.githubusercontent.com/assets/20285115/25169189/ff2a1e5e-24dd-11e7-8fb6-4886c39e3a16.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169192/0246db0e-24de-11e7-92e2-8da25a9253cb.png)

**Comment by suryanaga** [comment]
This isn't a problem, users don't need to install apps to go through Verify
