### ISSUE TITLE
Users need to be asked for dates in a consistent format so that they don't enter wrong information

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#409]
Users struggling to enter dates due to different date formats being used throughout.
![image](https://cloud.githubusercontent.com/assets/20285115/25169534/4aaf9272-24df-11e7-9e64-9f20ed0c902f.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169540/4f9f7284-24df-11e7-8414-9a7f01219645.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169551/55e9adbc-24df-11e7-851b-c8090dbb032d.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169554/589db120-24df-11e7-9395-eb8c910ecd6b.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169613/8962686e-24df-11e7-8056-ef362a01cc4a.png)
![image](https://cloud.githubusercontent.com/assets/20285115/25169618/8bf475e0-24df-11e7-88dc-43b475266e4f.png)

**Comment by colin2678** [comment]
what format was this information presented in during the research? This would impact how a user would fill in this information.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer I assume the prototype complies with the guidelines set out in the [service manual](https://www.gov.uk/service-manual/design/dates) - please can you confirm this? and if so, close this issue.

**Comment by suryanaga** [comment]
Yeah, the dates in the Argleton bit of the prototype use the pattern in the service manual. The stuff in the IDP part can't really be controlled.
