### ISSUE TITLE
Styling does not display application reference number

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#424]
@GWSunderland 

The last page where application reference number is displayed is white letters on white background and unless highlighted with a cursor is not visible to the user

![screen shot 2017-04-21 at 11 09 21](https://cloud.githubusercontent.com/assets/20285115/25273502/ea4f94e4-2683-11e7-85ac-905c303fa3c4.png)
![screen shot 2017-04-21 at 11 17 05](https://cloud.githubusercontent.com/assets/20285115/25273545/19d63c5e-2684-11e7-9a8c-64e537e59c25.png)

**Comment by GWSunderland** [comment]
@kenmaddison-scc Can we look at this please Ken and change either the font colour or background colour?

**Comment by EUzkuraityte** [comment]
duplicate of #327
