### ISSUE TITLE
Check if you need a permit:  The language used 'the area where you'd like to park' is unclear

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#427]
Impact: Users may not enter the correct postcode at this point.

Evidence: User questioned whether they should enter their home postcode or somewhere else where they would like to park.

**Comment by AbiBarkerOxfordshire** [comment]
Apologies!!! Not used to using GitHub so inadvertently closed this!

**Comment by EUzkuraityte** [comment]
resolved by #294
