### ISSUE TITLE
Apply for a permit: The cost of the permit is not clear

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#429]
Impact: Users may leave the application to try to find more information about the cost of permits.

Evidence: “Don’t see how long it lasts, so not clear on cost.”
I’d want to know the cost so that I could be sure I can cover the cost.”

**Comment by lizziebruce** [comment]
See #313

**Comment by suryanaga** [comment]
Duplicate of #313.
