### ISSUE TITLE
Prepopulate billing address field with current address

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#43]
From Pete: Billing address - Is there any opportunity to pre-populate? I know duplicate data entry is something people hate

**Comment by suryanaga** [comment]
Yep, that's a good spot. 

I imagine lots of council's payment component will be difficult to hand data to, but definitely worth saying in the pattern they should do it if possible.

Definitely worth integrating into the prototype as well. At least for now, probably worth having it show a made up address to users to confirm as it's difficult to get prototype to store user-entered data.

You can basically copy over the stuff I've done in #17 for this. Have a look in particular at the .js and .html in the Files Changed tab.

**Comment by suryanaga** [comment]
Actually going to close this for now, because we're going to test the first round as if the councils were using GOV.UK Pay and this probably wouldn't be a thing they would do (but it's something we can talk to them about if it comes up in research)
