### ISSUE TITLE
Users need to understand why they are being asked about sharing their personal data

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#431]
Impact: Users may abandon Verify at this point.

Evidence: “Will only check name and address – doesn’t address the issues so what’s the point?”
This user did abandon Verify and went back to the upload documents option.

**Comment by EUzkuraityte** [comment]
![screen shot 2017-05-11 at 16 28 56](https://cloud.githubusercontent.com/assets/20285115/25957796/06d2c4ea-3667-11e7-89fb-b224da9cb1bf.png)

**Comment by EUzkuraityte** [comment]
@lizziebruce I believe the page has changed since the issue was raised so pulling this into the 'Recent changes could affect this. Are we still seeing this need in research?' column. Will observe on Monday and decide if this needs further action

**Comment by petegale** [comment]
Not seeing evidence of this in Round 3
