### ISSUE TITLE
PP: Do you only ever have one permit?

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#44]
From Pete:
You already have a permit - Are we confident that it is always a simple 1-to-1 relationship? Especially when considering zones.

**Comment by suryanaga** [comment]
No, it's not always 1-1, different councils have different rules. Have tried to talk about this in the pattern page, but worth talking about more maybe.

Also worth mentioning here that I'm planning to build in a thing at the start of Alpha where councils can change these variables for their own versions of the prototype.

**Comment by suryanaga** [comment]
Closing this as I think the content in the pattern makes it clear this is only applicable for some councils.
