### ISSUE TITLE
Is putting Verify in front of the application process going to cause higher dropout?

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#45]
From Pete: Some councils that have a current My Account area had issues with users being unable to get through the account creation process, and so being put off the application process. Is putting Verify in front of the application process going to cause similar issues?

**Comment by suryanaga** [comment]
Yep, something to find out in research.

**Comment by petegale** [comment]
![screen shot 2017-03-03 at 15 27 56](https://cloud.githubusercontent.com/assets/2970019/23556886/fedfdefc-0025-11e7-9537-c9014d32067f.png)

**Comment by EUzkuraityte** [comment]
![screen shot 2017-05-03 at 12 52 52](https://cloud.githubusercontent.com/assets/20285115/25659388/73329f02-2fff-11e7-803a-7fad329487e4.png)

**Comment by petegale** [comment]
Closing this, as we have never tested any alternates to the basic service pattern of register before application
