### ISSUE TITLE
Application complete: Users were unclear that they had finished or what the reference number means

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#451]
Impact: Users are left feeling unsure they have successfully completed the process.
Evidence: “No payment successful screen.”
“Why do I want a reference number?”
“Payment confirmation – other online service end with this.”
“Want a payment receipt – would rather get this automatically than have to sign up for it.”

**Comment by EUzkuraityte** [comment]
Duplicate of #237
