### ISSUE TITLE
Users need to know how the council will be storing their vehicle registration data

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#452]
*Sorry if I've assigned the wrong people! My first 'new issue' creation..*

Orvokki Lohikoski advised @sanjaypoyzer and @lizziebruce on 24/04 that there's a need to flag how councils are storing vehicle registration data. Particularly as this is also attribute exchange.

**Comment by EUzkuraityte** [comment]
hI @lizziebruce I've changed the labels as this is a parking permit related item, also, this information is stored in the parking back office system together with the rest parking permit information. 

Strictly speaking this isn't attribute exchange, as there isn't going to be a central hub. However, it doesn't mean we shouldn't connect to the personal data exchange team about user consent driven data exchange. @sanjaypoyzer could you pick this up with Maria Izquierdo?

Lizzie, is there anything else that we would need to know from councils?

**Comment by lizziebruce** [comment]
@EUzkuraityte thanks, of course, a parking issue (it was a long day!). That's all I would need to know re storage for the copy.

**Comment by lizziebruce** [comment]
@EUzkuraityte Copy for re vehicle reg data privacy for Enter your vehicle details page and Upload your V5C page:

> Argleton County Council will store your vehicle registration data securely on our own system.

Questions: 
1. How long is data stored for? 
2. Does it need to be stored beyond the time of the online application – will it make renewals easier? Should we give user option for opt out for those who want their data deleted after application or does the council have to keep it for their records of who they've issued PPs to?

**Comment by EUzkuraityte** [comment]
@lizziebruce
1 - the information is checked and document copies received are destroyed after checking
2 - renewals are out of scope.. I'm not familiar enough with council processes to advice on this and I don't what their plans are going forwards. If we want scope to be extended to renewals, this would have to be proposed to Michael.

**Comment by lizziebruce** [comment]
@EUzkuraityte 
1. This doesn't answer my question. Let me make it clearer: 
How long is the electronic data users provide stored?

2. This isn't about renewals. Please re-read without the clause about renewals i.e:
Does it (electronic data) need to be stored beyond the time of the online application? Should we give user option for opt out for those who want their data deleted after application or does the council have to keep it for their records of who they've issued PPs to?

**Comment by EUzkuraityte** [comment]
@lizziebruce I'm now confused.. I thought this was about v5 but if not, could you specify which electronic data you'd like to know about? We can then circulate this question to our pilot participants.

The council keeps a record of the application as they have a max number of permits allowed per household and therefore need to know who has a permit, also, for enforcement purposes knowing about a user and his car is needed. So users would not have the option to request their data to be deleted

**Comment by lizziebruce** [comment]
@EUzkuraityte the vehicle registration data, which could be vehicle registration number or vehicle registration number plus V5C, plus the applicant's personal data input during the application, which also links them to a particular vehicle or vehicles. Your explanation about keeping the data for records and enforcement answers my query. No need to circulate to pilot participants. 

However the situation changes if they sell the car. Should we add copy to say "Contact the council to let us know if the vehicle changes ownership" or will this be on the permit itself? When the car is no longer in the user's ownership, and not sold to a member of their household, they should have the right to request the data is destroyed or at least updated, as it is no longer relevant for knowing the maximum number of permits for their household or for enforcement purposes.

**Comment by EUzkuraityte** [comment]
@lizziebruce It's an intesting one, it is definitely worth communicating the information re: change of vehicle but I think it's up to you and @sanjaypoyzer to decide how this should be done. This information wouldn't be on the parking permit but could be included in the notification or confirmation emails. I'm not convinced we should take it upon ourselves to write this, because due to local variations we're never going to be able to prove a piece of advice that fits all. For example, some councils would issue a refund if a permit needs to be cancelled, whilst others wouldn't. 

I think this fits in the 'other' use cases category which involves renewals / replacements / cancellations / change of vehicle and others. They are currently out of scope... I'm happy for you to include this into service pattern if you think it's necessary, but unless it comes up in user research as something that users need to know, I'd say let's keep the scope as is.

**Comment by lizziebruce** [comment]
@EUzkuraityte thanks for your explanation. That makes sense. I can create pattern copy / guidance for what the notification and confirmation emails should contain.

**Comment by EUzkuraityte** [comment]
@lizziebruce are you able to mock up a link to page that would explain to the user hoe the council will use the vehicle data and include it in this page and any others you think might be relevant (i.e. once we have the pages where a user could enter the further vehicle details like make, colour see: #145)?
![screen shot 2017-06-19 at 10 08 29](https://user-images.githubusercontent.com/20285115/27278524-8e2849fc-54d9-11e7-9aea-bcde4acba913.png)

**Comment by lizziebruce** [comment]
Re reg number storage: Is the user a) concerned about who will be storing it and where or b) concerned that Cambridgeshire County Council are storing it? It would be helpful to know whether or not the user saw and read the copy just below the enter reg number field:

> Cambridgeshire County Council will store your vehicle registration data securely on our own system.

Re privacy policy please see #41 this should be a link in the council website footer and so would appear on every page

**Comment by lizziebruce** [comment]
@EUzkuraityte closing this issue as the content asked for is already all there on the page. Only one user has missed the information about how the data will be stored and used. 
For Privacy policy see #41.
