### ISSUE TITLE
Privacy requirements – full details

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#453]
Orvokki Lohikoski advised @sanjaypoyzer and @lizziebruce on 24/04 that there's a need to flag how personal data is stored. Key information that the user may be concerned about should be contextualised in the on-page copy. Full details of all data storage should be accessible throughout the user journey, but it is ok to do this in a tradional way for example a footer link.

**Comment by EUzkuraityte** [comment]
I think it's a duplicate of #41 so closing this one and copying this comment to the original issue
