### ISSUE TITLE
Content changes

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#456]
Please see https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1b9rLsp0rQF199U4JLsZtNezuQR9kCI_U-hkHl6E3N6w/edit?usp=sharing for a holistic set of content fix recommendations to encourage less drop off through the user journey.

Multiple related content fix issues, including: 
#454 #360 #356 #298 #332

**Comment by suryanaga** [comment]
## Start page
 - [x] "support" -> "help"

## Check boundary page 
 - [x] Remove "To check if you need a permit,"

## Resident's start page
 - [x] "Resident's parking permits cost" -> "A resident's parking permit costs"
 - [x]  "These permits allow" -> "This permit allows"
 - [x]  Remove link to postcode checker

### About your application
 - [x] "Each household..." -> "maximum 4 resident’s permits per household"
 - [x] Remove "To apply" from bullets
 - [x] "permits take 5 working days to arrive – we’ll email you a temporary permit to use while you wait"
 - [x] Apply by post: 
>Print and send an application form or a letter to Argleton County Council with scanned copies of your:
>
>    - council tax statement
>    - identity document with proof of your age
 - [x] Capitalisation on the address

## Non-verify route start page
 - [x] Remove in flow

## Proof of address page
 - [x] Amend content to: 

> Scan and upload a proof of address document. This can be a recent:
> 
> council tax bill 
> utility bill 
> tenancy agreement or mortgage statement
> 
> The document must show your name and your current address.
> 
> 
> We'll check your documents as part of your application.
> 
> Upload document
> 
## Document accepted
 - [x] "You now need to give us some details about your vehicle."

## Enter vehicle details
 - [x] "vehicle details" -> "vehicle registration number"
 - [x] "associate" -> "link"
 - [x] hyphen -> `&ndash;`

## Permit length
 - [x] Remove "costs"

## You're about to pay
 - [x] "month" -> "months"

## How do you want to pay
 - [ ] Move charges info to bottom
 - [ ] brackets -> hyphen

## Enter card 
 - [x] "month" -> "months" (payment summary)

## Direct debit
 - [x] Add months to payment summary

## Confirm payment
 - [x] "Payment of" -> "Payment for"

## Success page 
 - [x] "permit" -> "parking permit"
 - [x] "In the mean time" -> "Until your parking permit arrives, "
 - [x] "About your.." - > "Important information about your.."
 - [x] bullets:
>  - Display your permit clearly in your front car window when parking in Argleton city centre to avoid a fine.
>  - You can park in Argleton city centre at any time with your your parking permit displayed.
>  - Your permit expires in 12 months. You'll receive an email and text when your permit expires.
 - [x] "You can also use your GOV.UK Verify account to access other government services like:
 - [x] Reduce list of services to:
> - claim your redundancy payment and monies owed
> - check your State Pension
> - sign in to your personal tax account

**Comment by lizziebruce** [comment]
@EUzkuraityte these are now live!

**Comment by EUzkuraityte** [comment]
Amazing! Many thanks @lizziebruce

**Comment by suryanaga** [comment]
Closing this issue as the fixes are now done.
