### ISSUE TITLE
Users need to know what is meant by ‘identity questions’

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#464]
Impact: This caused some uncertainty in choosing Verify.

Evidence: Several users questioned the meaning of ‘identity questions’ at this point, yet still chose the ‘Verify’ option, primarily to avoid having to scan and upload documents.

**Comment by lizziebruce** [comment]
"identity questions" has been replaced with "security questions" and tested well with PP users.

**Comment by irinapencheva** [comment]
@lizziebruce - happy to have this closed but do you / @petegale think there's benefit in keeping in mind for CT testing as well since it's different demographic who were a lot more concerned about privacy and security?

**Comment by petegale** [comment]
Happy to see this closed. If it's still a problem it will emerge in the next CT testing

**Comment by irinapencheva** [comment]
In order to make sure we track this , I'll reopen this issue but move it to the column 'Recent changes have been made. Are we still seeing this in research?'

**Comment by suryanaga** [comment]
Closing this as it's not coming up in research any more.
