### ISSUE TITLE
Most users said they did have a (physical) photo, but never got a chance to use it.

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#466]
This user journey confused users, as they were asked about a photo that seemed relevant, yet never given an opportunity to use it.

Some who were told to do to a photo store would abandon the process at that point.

Some tried to click back and find an alternate route.

**Comment by suryanaga** [comment]
I've ammended PR #334 so that the word 'digital' is included on the "You need a photo page" in the first sentence and in the question:

![screenshot-localhost-3000 2017-04-28 13-26-31](https://cloud.githubusercontent.com/assets/4106955/25528607/98249a14-2c16-11e7-922b-ee3638cb1988.png)

**Comment by petegale** [comment]
closed as a duplicate of #301
