### ISSUE TITLE
Users needed to receive notifications but were frustrated at having to re-enter their contact details from Verify

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#469]
![screen shot 2017-04-26 at 11 53 12](https://cloud.githubusercontent.com/assets/24913176/25431074/f7b3d194-2a76-11e7-9f13-d8d7095babbd.png)
Though the fact that details were remembered on the second page improved this, it was still an issue for some.

**Comment by suryanaga** [comment]
@irinapencheva Considering the information gets passed between the two screens, I'm not sure what this has to do with users needing both confirmation and reminder messages?

**Comment by irinapencheva** [comment]
This is literally what we observed in User Research so could discuss if we just deprioritise it as an issue, but I think it should be captured.

**Comment by suryanaga** [comment]
I don't think we're seeing this issue as much since moving to LOA1.

**Comment by irinapencheva** [comment]
![screen shot 2017-06-14 at 16 20 34](https://user-images.githubusercontent.com/24913176/27140437-6fc52ecc-511d-11e7-9ac4-60500a2de3ab.png)
Still seen in user research but will close it as it is not in scope for Alpha and should be fed back to the wider Verify improvement team
