### ISSUE TITLE
At the end of the transaction, users still wanted to know more about exactly when and where they could use their passes but couldn't

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#472]
There was little or no recall of the information provided on the start page.

![screen shot 2017-04-26 at 11 58 59](https://cloud.githubusercontent.com/assets/24913176/25431334/09a3ea3c-2a78-11e7-9436-6540200ff8a8.png)

**Comment by lizziebruce** [comment]
The content for the Application complete page has been revisited in the Content design review.

Specifically relevant here:

> <img width="517" alt="screen shot 2017-04-28 at 17 29 12" src="https://cloud.githubusercontent.com/assets/27814324/25537883/4a1a0abc-2c38-11e7-9e09-cc514789da5b.png">

**Comment by irinapencheva** [comment]
@lizziebruce - I like the above without the link to the local council as discussed

**Comment by petegale** [comment]
Limited evidence (2 users) from round 3 suggests this may be addressed, though not yet conclusive

**Comment by petegale** [comment]
Closing this as not seen in Northumberland research, adding to evidence above
