### ISSUE TITLE
Users need to take  selfie with a webcam but can't do so

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#474]
Build and test ability to test a photograph using in-built webcam on browser

**Comment by irinapencheva** [comment]
#334

**Comment by suryanaga** [comment]
Just for clarification, this feature is for desktop users who have a webcam in, or connected to, their computer to be able to take a photo without leaving their browser.

**Comment by irinapencheva** [comment]
![screen shot 2017-06-14 at 16 05 55](https://user-images.githubusercontent.com/24913176/27139622-6755a3ea-511b-11e7-9fc3-905ced08301d.png)
This issue can be closed as found in UR.

It only requires a minor content fix to address the below issue
![screen shot 2017-06-14 at 16 06 41](https://user-images.githubusercontent.com/24913176/27139689-96a1199a-511b-11e7-982d-6b40979c78ac.png)

**Comment by lizziebruce** [comment]
@irinapencheva I don't think there's anything we can do to add any further clarity. The UR note above says the screenshot attached (which is the current live prototype) show the updated version of the page "that addresses this issue". I think this is already solved!

Users with a webcam not attached to the computer will need to either attach the webcam to their computer or if it's inaccessible in a drawer etc choose No or I'm not sure.
