### ISSUE TITLE
Users need to know which permit they are applying for

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#475]
![screen shot 2017-05-03 at 12 16 19](https://cloud.githubusercontent.com/assets/20285115/25658387/83f6b044-2ffa-11e7-81e8-d35764b412f7.png)

**Comment by EUzkuraityte** [comment]
similar to #294

**Comment by lizziebruce** [comment]
See #294 
Prototype now outlines types of permit available from universal Start page. The specific permit type for each user won't be detailed til after they have input postcode.

**Comment by suryanaga** [comment]
Let's see if this still comes up in research with the changes we've made recently before closing this.

**Comment by lizziebruce** [comment]
Adding screenshot to show the recent changes made to prototype which have supported this need:

![screen shot 2017-05-22 at 12 22 12](https://cloud.githubusercontent.com/assets/27814324/26305971/685188e8-3ee9-11e7-8df4-c903a874a451.png)
