### ISSUE TITLE
Users were unaware of temporary passes as a benefit to verified applications

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#477]
![screen shot 2017-05-03 at 12 51 13](https://cloud.githubusercontent.com/assets/20285115/25659349/4d48273a-2fff-11e7-81f1-0b6089551313.png)

**Comment by ingasiler** [comment]
![image](https://cloud.githubusercontent.com/assets/19390851/25745579/7344c17a-3197-11e7-890c-5af2cbe25e2d.png)

**Comment by ingasiler** [comment]
related to #238

**Comment by ingasiler** [comment]
This sheet contains LAs responses on whether they are currently using temporary permits, and if they have examples of it: https://docs.google.com/a/digital.cabinet-office.gov.uk/spreadsheets/d/17nsMnjANk_-5T_rU0afb1CscPLshmvKyF_DXqRh_4kU/edit?usp=sharing

**Comment by petegale** [comment]
Round 3 suggests that users are now aware of temporary permits as a benefit of Verified application
![screen shot 2017-05-22 at 10 49 08](https://cloud.githubusercontent.com/assets/2970019/26302633/c9a572b0-3edc-11e7-9f93-22164831a394.png)
