### ISSUE TITLE
Research question: To what extent does Verify at LOA1 present a barrier to users?

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#483]
![screen shot 2017-05-03 at 15 08 18](https://cloud.githubusercontent.com/assets/20285115/25664386/5dc50c6e-3012-11e7-824a-0bc0f0d4b4ee.png)

**Comment by ingasiler** [comment]
For less digitally skilled users there was only one viable option to get verified with LOA1 #480

**Comment by petegale** [comment]
![screen shot 2017-05-22 at 11 31 00](https://cloud.githubusercontent.com/assets/2970019/26304151/2b6b3b56-3ee2-11e7-97df-e67a70fb82ac.png)

**Comment by irinapencheva** [comment]
![screen shot 2017-06-14 at 14 46 46](https://user-images.githubusercontent.com/24913176/27135421-591b127a-5110-11e7-8c6c-a0c9d49b4166.png)

Finding from ConTravel  user research
