### ISSUE TITLE
Research question: Can tablet users complete the service without assistance? 

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#484]
![screen shot 2017-05-03 at 15 10 38](https://cloud.githubusercontent.com/assets/20285115/25664527/c8ea297a-3012-11e7-93b2-16b4c0a62171.png)

**Comment by petegale** [comment]
Tested again in R3 - appears that they can, provided they don't have to upload a V5C. Keeping this open until clear on status of V5C upload

**Comment by EUzkuraityte** [comment]
I'm closing this issue as our pattern and prototype recommend not using any type of doc upload, including V5C
