### ISSUE TITLE
Users chose the same settings for both confirmation and reminder emails

### ISSUE THREAD

**Issue by ingasiler** [alphagov/verify-local-patterns#486]
![image](https://cloud.githubusercontent.com/assets/19390851/25744960/8e141814-3194-11e7-9754-98e7ccc330bf.png)

**Comment by ingasiler** [comment]
Link to #449

**Comment by EUzkuraityte** [comment]
evidence form Oxford:

Impact: Users might make mistakes as they become increasingly frustrated.
Evidence: “You know my email address and telephone number, why do I have to type it again?”

**Comment by EUzkuraityte** [comment]
closed via #449
