### ISSUE TITLE
Which advice is better understood by users re: free 1st permit for household?

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#487]
A/B testing required to come up with a final version

> The first parking permit for each household is free.

Could we do A/B variation user testing where if users didn't understand that they are given this longer copy?

> The first parking permit for each household is free. If it's the first time you're applying and no one else who's currently living at your property has applied, there'll be no cost for your permit.

**Comment by petegale** [comment]
We can test these to see what problems they generate / whether they are understood. It's not valid to test which people 'prefer'. Also worth noting A/B tests are typically quantitative tests with much larger sample. It's not clear what goal we would be testing against if we were to A/B test this in beta

**Comment by EUzkuraityte** [comment]
@petegale agreed, changed the title to reflect your suggestion better.
@lizziebruce the A/B testing was requested by you in #297 . Please advice re: Pete's comments above.

**Comment by lizziebruce** [comment]
@petegale A/B may not be the correct term for it. I know it sometimes happens that URs start the day testing one version and if it's obvious people don't get it at all they change to another with added clarity – this was demo'd to us in the GDS Design training on user research. 

So I'd suggest starting with:

> The first parking permit for each household is free.

and if it consistently confuses people show later users:

> The first parking permit for each household is free. If it's the first time you're applying and no one else who's currently living at your property has applied, there'll be no cost for your permit.

If this method isn't what you'd recommend then let's just test the first option and see if people understand!

**Comment by lizziebruce** [comment]
@EUzkuraityte I created the second option as you believed the users would be confused by the first. I don't think the second option is necessary but as I said we can see what users think.

**Comment by EUzkuraityte** [comment]
@lizziebruce ok, thanks

**Comment by EUzkuraityte** [comment]
Closing this issue as it was not observed in UR
