### ISSUE TITLE
Users wanted more information about the documents referred to on the start page [in the upload documents path], but were unable to find enough information about that

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#491]
“If I’m going to need any documents, I’d like to know what they are now, so I’m ready”

**Comment by lizziebruce** [comment]
@EUzkuraityte Please let me know what documents these would be so that I can add copy referencing them.

**Comment by irinapencheva** [comment]
@lizziebruce - I'll take this with Camden as it's a ConTravel issue

**Comment by lizziebruce** [comment]
@irinapencheva thanks, this is the copy that shows on the page after the Start page at the moment:

![screen shot 2017-05-12 at 10 40 29](https://cloud.githubusercontent.com/assets/27814324/25992907/ffad8ea4-36ff-11e7-892c-2746262267b6.png)

**Comment by irinapencheva** [comment]
Cool, thanks. I'll double-check what docs are accepted

**Comment by petegale** [comment]
Users in round 3 were reading this page quite carefully and making informed decisions based on the information provided
