### ISSUE TITLE
Users have to answer identity questions but they weren't sure they'd know the answers to those 

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#498]
Users were concerned they might fail the identity test despite being legitimate users [Medium]
“I can’t remember when I moved in”.
“I wouldn’t know when I last took out a mobile phone contract. I’d just have to guess”

**Comment by irinapencheva** [comment]
@lizziebruce - this issue was raised by Camden. Do you think there's anything in the content we can add to reassure them they're likely to know the answers? Or is that overkill/ should be covered by the Verify journey?

**Comment by lizziebruce** [comment]
@irinapencheva Hmm. I think this is an issue for Verity hub to resolve. We can't assure them they're likely to know the answers as they might not (especially given the demographic). But I know what you mean. However, the issue shouldn't come up IRL as, as far as I know, the Verify hub questions will be tailored to recent activity that the user should find easy to recall. So here it is better to do nothing – as we expect the problem won't actually arise.

**Comment by irinapencheva** [comment]
@lizziebruce - cool, happy with it!
