### ISSUE TITLE
Do users need to understand that price is calculated per household

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#510]
Need to check if at this page users understand that the 1st permit for the household (not the user) is £51

![image](https://cloud.githubusercontent.com/assets/20285115/25893623/6a968ffe-3570-11e7-9d96-6a6ff440ad39.png)

**Comment by petegale** [comment]
Final PP iterations during alpha suggest that users understood that costs were per household and not per individual.
