### ISSUE TITLE
PP: Amend checking permits advice

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#52]
Section: What is the user journey? 9. Checking permits

1. 'where they can pick up their permit from to get it faster' change to 'if they can pick up their permit from a council office to get it faster and where from' 

2. add to the list 'advice on how customers can park without their permit until they receive it'

**Comment by kaydale** [comment]
10. Checking permits
It's better for users and cheaper for government if the permits are issued electronically. Wardens check the permits by entering number plates into a database.

Councils who haven't yet moved over to an electronic permit system, should have a plan in place to move over.

In the meantime, councils should mention in the payment receipt

- how long they will need to wait for a permit to be posted to them
- if they can pick up their permit from a council office to get it faster and where from
- if they can print a temporary permit themselves while they wait for a permanent one
- This information should also be communicated on the council's start page at the beginning of the user journey.
- advice on how customers can park without their permit until they receive it

Temporary permits should clearly show their expiry date so wardens and users can check them easily.
