### ISSUE TITLE
Users need a clear explanation of what to do if they cannot park in their preferred area

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#527]
Hi @lizziebruce I realised that this page is not accessible via the main prototype as this is an eventuality when a user cannot park in their preferred area. This age is found via the service pattern. I'm not sure if you picked it up as part of the prototype review you did in the beginning, but please let me know if you have. 

Link:
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/no-permits

**Comment by lizziebruce** [comment]
@EUzkuraityte no I haven't seen this page before. This is the sort of thing that drawing up the user journey will flush out. I'll refer to the service pattern to inform the drawing. It's also a useful tool for a visualisation and deeper understanding of the user journey. 
Let me know if content review for this page is a high priority.

**Comment by EUzkuraityte** [comment]
Hi @lizziebruce sounds good to me! It would be good to have this worked on this sprint, but it's not top priority. I've put it in the right priority order in the 'PP ready to do' column.

**Comment by lizziebruce** [comment]
@EUzkuraityte great thanks. I've added the None available page to the user journey map. Will review content once I get to it in PP ready to do! 

![parking permits user journey map](https://cloud.githubusercontent.com/assets/27814324/26211064/72aecd58-3be9-11e7-915e-420af0904e36.jpg)

Updated!

https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1YvEJKqGvyOW0Lbth2P10nuMto4n5ylrhaJAy2ja6U2s/edit?usp=sharing

**Comment by lizziebruce** [comment]
@EUzkuraityte I've made a copy rewrite for the No permits available page here, with tracked changes from the prototype copy: https://docs.google.com/a/digital.cabinet-office.gov.uk/document/d/1_6jGK1pIJn-G_HNuxTRXvQCsnZ4Qs1Wkdr_7_OaQWgM/edit?usp=sharing 
I think we should offer an option for if people don't want to apply elsewhere and would rather wait for a permit to come up in their preferred area. Could you find out if councils have waiting lists for oversubscribed areas?

**Comment by EUzkuraityte** [comment]
Hi @lizziebruce the only council that has waiting lists as far as I know is Brighton (but they dropped off from the pilot..) 

I will check with current pilot participants to confirm if they use waiting lists

**Comment by lizziebruce** [comment]
@EUzkuraityte @sanjaypoyzer  FYI copy edits screenshot here:

<img width="567" alt="screen shot 2017-05-26 at 10 23 48" src="https://cloud.githubusercontent.com/assets/27814324/26489020/8c52128c-41fd-11e7-8c7d-8cb03d7f9632.png">

**Comment by lizziebruce** [comment]
👍
