### ISSUE TITLE
BUG: Bucks prototype wrong redirecting after Verify journey

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#539]
@sanjaypoyzer I've had a look at Bucks parking permit prototype and it seems to direct to concessionary travel pages after the Verify journey. @colin2678 can you confirm if you're seeing this issue as well?

**Comment by colin2678** [comment]
@EUzkuraityte Yes it does. Very strange.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer is there something we can help with?

**Comment by suryanaga** [comment]
fixed this just now
