### ISSUE TITLE
Contravels: Renewals notification add billing address on dropdown

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#54]
on this page:
/service-patterns/concessionary-travel/example-service/renewal-notification
If the user selects the "Letter (send to billing address)" option we should show the billing address in a dropdown.

**Comment by irinapencheva** [comment]
@kaydale - what do you mean by 'billing address'? In ConTravel there's no payment, so might be confusing

**Comment by kaydale** [comment]
@irinapencheva You're totally right - this should say something about verified address. The issue is relate to this page https://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel/example-service/renewal-notification

**Comment by irinapencheva** [comment]
Great, yep, just a minor change then. Thanks!
