### ISSUE TITLE
What happens to the NI number captured by GOV.UK?

### ISSUE THREAD

**Issue by BeckiBorastonBucks** [alphagov/verify-local-patterns#544]
After being verified successfully through a company, the customer is taken to a GOV.UK screen to input their NI number before they return to the council's form.

- Why does GOV.UK ask for this information when the customer has already been verified? (there is no explanation on the page)
- How can the council retrieve this information?
- If the council cannot retrieve this information when the customer is sent back to us, can we remove this stage and add it to the council's form instead?

**Comment by EUzkuraityte** [comment]
@BeckiBorastonBucks many thanks for spotting this! I've not seen [this page](https://govuk-verify-loa1.herokuapp.com/third-cycle-matching?above_age_threshold=true&action=register&apps=true&bank_account=true&credit_card=true&debit_card=true&driving_licence=true&driving_licence_issuer=true&idp=barclays&mobileNumber=&mobile_phone=true&passport=true&requestId=parking-permit-sunderland&resident_last_12_months=true&selection=true&userLOA[0]=0&userLOA[1]=2&firstName=&middleName=&lastName=&dobDay=&dobMonth=&dobYear=&building=&street=&town=&county=&postcode=&movemonth=&moveyear=&loa1Method=kbv&idTest3=lessThan2&loa1_kbv_done=true) before. @sanjaypoyzer would you know if this page is present for both LOA2 & LOA1 journeys and why is the user being asked for it?

**Comment by suryanaga** [comment]
Looks like this has now been taken off, I think it was something the LOA1 team were testing for the 'View driving license' service.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer I'm reopening this issue as we observed this during UR. Could you work with LOA1 team to ensure this does not show up during PP UR this week?

Let me know if there's anything I can do to help.

**Comment by suryanaga** [comment]
This is being taken out of the prototype.
