### ISSUE TITLE
Transfer your photo to this computer - what if the user is on mobile/tablet?

### ISSUE THREAD

**Issue by BeckiBorastonBucks** [alphagov/verify-local-patterns#547]
Should there be a different message if the user is on a different device?

**Comment by suryanaga** [comment]
They won't see this page in that case - The prototype detects the device and routes them to a different page.

**Comment by BeckiBorastonBucks** [comment]
Do you have anywhere that lists all of the technical functionality of the forms that we need to be aware of in order to build it? This as an example of something that is not obvious when filling it in and something we need to investigate with our suppliers on how to build.
