### ISSUE TITLE
You need a parking permit - Oxfordshire - visitors do no qualify

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#548]
The page asks if you are a resident or visitor and if you are a visitor asks you to apply for a visitors permit however the rules in Oxfordshire are that only residents qualify for a visitors permit. We would need either a third option 1) I am a resident with a vehicle (apply for a parking permit)  2) I am a resident without a vehicle (apply for visitors permits) or 3) I am a visitor (you can't have a permit)

**Comment by EUzkuraityte** [comment]
@AbiBarkerOxfordshire this page is waiting to be updated, please see for new copy here #515 and advise if this would not work for your council.
