### ISSUE TITLE
Confirmation messages: Oxfordshire - bug?

### ISSUE THREAD

**Issue by AbiBarkerOxfordshire** [alphagov/verify-local-patterns#552]
This page appears to have no header or foot or styling? Not sure if this is a bug?

**Comment by EUzkuraityte** [comment]
@AbiBarkerOxfordshire Hm, I'm not sure.. This is what I see on my machine and it looks alright!
![screen shot 2017-06-08 at 09 58 16](https://user-images.githubusercontent.com/20285115/26920505-2308f2e4-4c31-11e7-9cf0-8f89a5806980.png)
![screen shot 2017-06-08 at 09 58 02](https://user-images.githubusercontent.com/20285115/26920509-2528248c-4c31-11e7-9d11-754745e6c0de.png)

Are you able to provide some screenshots?

**Comment by AbiBarkerOxfordshire** [comment]
@EUzkuraityte I have just re-checked and it's fine now!! So sorry - happy for this to be closed. Thanks, Abi
