### ISSUE TITLE
User will not enter card details due to security concerns . 

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#566]
![issue 8](https://user-images.githubusercontent.com/27288208/27036646-6f89a470-4f7d-11e7-9387-f7bf1173ace3.PNG)

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer @lizziebruce is there anything we could do to reassure the user of how safe it is to pay online?

**Comment by lizziebruce** [comment]
In my opinion, this is beyond the scope of this prototype.
