### ISSUE TITLE
User provided email/ mobile number on a number of occasions.

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#568]
![issue 10](https://user-images.githubusercontent.com/27288208/27036725-ac306cb0-4f7d-11e7-84c2-72c7289b0955.PNG)

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer @lizziebruce I feel like we had a discussion about this previously.. Is there a reason why we couldn't pull the email address from here

![screen shot 2017-06-12 at 15 20 48](https://user-images.githubusercontent.com/20285115/27038509-2f0de3a6-4f83-11e7-8b61-24b87572adf0.png)

to here
![screen shot 2017-06-12 at 15 21 03](https://user-images.githubusercontent.com/20285115/27038516-34eab998-4f83-11e7-875c-8944bf481f92.png)

and give the user the option to change the field if they wanted?

**Comment by lizziebruce** [comment]
@EUzkuraityte re whether it is technically possible, I can't comment. Re user journey flow agree would be a good idea in theory – we'd need to flag that we were storing the email for notifications on the billing page though, so would result in putting the notifications info on the billing page and then that's asking them to do more than one thing at once. Would be happy with that for this demographic myself, e.g. with a sub-header Renewal reminder. But may not fit service design standards. Cos they might skip past it and miss out on chance for reminder. Let's discuss? Or just get @ Sanjay's opinion?

**Comment by EUzkuraityte** [comment]
@lizziebruce I completely agree, if this gets implemented we should incorporate the appropriate messaging
@sanjaypoyzer  please can you confirm if this can be done? also, do you have any concerns from the SD point of view?

**Comment by suryanaga** [comment]
Pulling email from the payment screens completely depends on the payment provider. My guess is it won't be possible.

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer our prototype screen asks the user to enter the email address to receive a payment confirmation. Can we have it as a 'recommended' feature to councils - if a user enters an email address, then we will pre-pop all further email address fields? Can you make this happen in the prototype?

**Comment by suryanaga** [comment]
@EUzkuraityte I really don't think payment providers will have that feature, as it would be a complicated thing for them to be providing to their customers at no real benefit. Can you check if this is something Worldpay would do?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer well, Northumberland already has it (screenshot attached) and as we're recommending that the field should be there, could we set up for our prototype (as a good practice thing) and not enforce it if councils struggle with it?

![image](https://user-images.githubusercontent.com/20285115/27084186-da9e7450-5042-11e7-9cb4-2232333c6477.png)

**Comment by suryanaga** [comment]
I'm talking about payment providers passing the email onto the council, not the payment provider asking for the email.

I'm closing this issue as it doesn't express a user need.
