### ISSUE TITLE
Users do not understand the GOV.UK verify account links at the end of the application

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#569]
![issue 11](https://user-images.githubusercontent.com/27288208/27036790-e6393428-4f7d-11e7-8859-663bb2ce581b.PNG)

**Comment by EUzkuraityte** [comment]
I'm tagging in @lizziebruce @sanjay to advice on making this a bit clearer to the user. 
Also, as we'll be doing user research tomorrow, we'll keep watch on how many users this issue affects.

**Comment by suryanaga** [comment]
Yeah, I think if they are confusing people we'll probably just take them out.

**Comment by lizziebruce** [comment]
How about adding a little bit of explanatory copy:

**Before**

> **Using your GOV.UK Verify account**
> 
> You can use your GOV.UK Verify account for other government services including:
> 
> - view or share your driving licence information
> - check or update your company car tax
> - complete your Self Assessment

**After**

> **Using your GOV.UK Verify account**
> 
> As part of your application you created a GOV.UK Verify account. You can re-use it for other government services, like:
> 
> - view or share your driving licence information
> - check or update your company car tax
> - complete your Self Assessment

**Comment by EUzkuraityte** [comment]
@lizziebruce looks great to me!
My only suggestion would be - is it possible to change 'Self Assessment' bit to '[Report a medical condition that affects your driving](https://www.gov.uk/report-driving-medical-condition)? - it's more relevant to parking and should be less alarming to users.

**Comment by suryanaga** [comment]
I'm not sure this section is needed. People seem to understand Verify much better in general now the content that introduces it is much better.

**Comment by lizziebruce** [comment]
@EUzkuraityte if the Verify links are confusing users here, it might be best to remove that section. The services flagged aren't a natural flow for the user in terms of being highly relevant to the service they've just applied to.

**Comment by EUzkuraityte** [comment]
@lizziebruce @sanjaypoyzer let's see tomorrow if/what users find confusing and take it from there!

**Comment by lizziebruce** [comment]
Egle's suggested maybe just a link to https://www.gov.uk/government/publications/introducing-govuk-verify/introducing-govuk-verify#government-services-you-can-use-with-govuk-verify since the Verify links section isn't being looked at (users saying they thought they could reuse on Ebay so they are just guessing). We could make this just one button, saying something like "Use GOV.UK Verify on other services."
Would be interesting to pick out whether people pay more attention to the Verify reuse on the confirmation email, I don't think there were any comments.

**Comment by suryanaga** [comment]
Having a link to a page like that is more future-proof too, which is good. (i.e It will be updated as other services use Verify)

**Comment by lizziebruce** [comment]
This has been implemented. Issue appears not to have come up again in user research. 

![screen shot 2017-07-20 at 10 37 24](https://user-images.githubusercontent.com/27814324/28411036-7d152ccc-6d37-11e7-93e5-cbc9bdc98f45.png)

**Comment by suryanaga** [comment]
@petegale to confirm close?

**Comment by petegale** [comment]
Didn't see this in the most recent rounds, can reopen if it emerges again. Before we do so, @lizziebruce  @anthonylord : Is it right to talk about " your GOV.UK Verify account" when the account is with the IDP?
I know in the past we avoided saying this, not sure how that thinking has evolved

**Comment by lizziebruce** [comment]
@petegale my understanding is it's ok to call it GOV.UK Verify account. have just asked Ant & will feed back his reply.

**Comment by lizziebruce** [comment]
Spoke to Ant and he confirmed your understanding Pete. I'd come up with this workaround which he's happy with:

![screen shot 2017-07-26 at 12 05 31](https://user-images.githubusercontent.com/27814324/28618084-fa672550-71fa-11e7-9625-1f558456f0b0.png)
