### ISSUE TITLE
User unsure whether the application was complete 

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#570]
![issue 12](https://user-images.githubusercontent.com/27288208/27036825-082e34ac-4f7e-11e7-93dc-db2c4c247064.PNG)

**Comment by EUzkuraityte** [comment]
@GWSunderland could it have something to do with the styling.. 
![screen shot 2017-06-12 at 15 04 30](https://user-images.githubusercontent.com/20285115/27038037-c0752388-4f81-11e7-83bf-762d05cbbf81.png)

As we're having UR on Wed, it will give us a good opportunity to observe this issue as well

**Comment by lizziebruce** [comment]
See also pull request #603

**Comment by EUzkuraityte** [comment]
Closing this issue as per UR findings
