### ISSUE TITLE
User needs the process to be quick and easy

### ISSUE THREAD

**Issue by GWSunderland** [alphagov/verify-local-patterns#571]
![issue 13](https://user-images.githubusercontent.com/27288208/27036879-2e4f0ae4-4f7e-11e7-951e-4d6d43bc5f8b.PNG)

**Comment by lizziebruce** [comment]
This is a basic online journey need that we're aware of as service and content designers and we attempt to solve within the constraints of the multi-stage multi-organisation user journey. I don't think we can "solve" it as an "issue" as such so am closing.
