### ISSUE TITLE
User won't be able to apply by phone but it says they would be able to do so

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#575]
On the 'Other ways to apply' there is an option to apply by phone, which councils don't usually have as an option so should be removed 
![screen shot 2017-06-13 at 17 05 45](https://user-images.githubusercontent.com/24913176/27092305-b7c66394-505a-11e7-946a-66bb29687549.png)

**Comment by lizziebruce** [comment]
@irinapencheva hadn't heard of this before... shall we discuss?

**Comment by irinapencheva** [comment]
@lizziebruce - In hindsight, let's keep it on the common prototype as some councils might have phone applications and the common prototype should reflect examples of all other possible ways to apply.
