### ISSUE TITLE
Users will be able to prove their identity with not just utility bills but currently says they have to upload ' a recent utility bill' 

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#576]
![screen shot 2017-06-13 at 17 11 50](https://user-images.githubusercontent.com/24913176/27092479-6cfc7014-505b-11e7-816a-a58db2fbdb3c.png)

**Comment by lizziebruce** [comment]
@irinapencheva what are the other options please? Would like to say what the actual needed things are rather than "proof of address", as then users can know whether they have the right thing early on

**Comment by irinapencheva** [comment]
@lizziebruce - is this screen still changing as per the PP discussion? I just had a chat with Egle and if both versions are tested in the PP user research I'm happy to go with the one that tests and reads better 

Actual evidence that could be used to prove address includes: bank statements, council letters, tenancy agreement, property documentation, other official document from the council or government that has your name and address

**Comment by lizziebruce** [comment]
@irinapencheva sounds good. Since there are so many variables, i.e.

"a letter or document with your address from your bank, council, mortgage lender or landlord or the  NHS, or a utility bill."

I think we'll have to say "proof of address" in the bullet and list them out as soon after in the journey as possible.

**Comment by irinapencheva** [comment]
@lizziebruce - yep, agree with the above approach

**Comment by lizziebruce** [comment]
Done

![screen shot 2017-07-03 at 11 53 37](https://user-images.githubusercontent.com/27814324/27789943-48f297c6-5fe6-11e7-9b3e-e01c9d2dd68c.png)
