### ISSUE TITLE
User will not receive a confirmation email within a minute but it says so 

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#578]
If we are enabling the functionality of the user to have the ability to change their address within 5 minutes of the application completion page, we should wait with sending the confirmation email until that time has lapsed

![screen shot 2017-06-13 at 17 21 06](https://user-images.githubusercontent.com/24913176/27092867-bae581d4-505c-11e7-80fd-c642b2e8897f.png)

**Comment by lizziebruce** [comment]
@irinapencheva Changed to "within the next 10 minutes". Let me know if you think it should be "w/in the next 6 mins" @sanjaypoyzer 

<img width="554" alt="screen shot 2017-06-29 at 15 13 42" src="https://user-images.githubusercontent.com/27814324/27692070-afffcfe4-5cdd-11e7-8538-85c6b0e621b1.png">

**Comment by irinapencheva** [comment]
@lizziebruce - cool - I'd keep it 'within 10 mins' to give enough time.
