### ISSUE TITLE
User will be able to tap their pass when using it but currently doesn't say so on the instructions for using the pass 

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#579]
![screen shot 2017-06-13 at 17 26 40](https://user-images.githubusercontent.com/24913176/27093155-8d1ca038-505d-11e7-86b1-6a2a05c392da.png)

On the first bullet it says the user has to show the pass to the driver but in many councils the user just needs to tap the pass on the machine and only show it to inspectors if necessary

Also on that bullet - would it make sense to remove the 'bus' of 'bus pass' in the bullet 'bring your bus pass when you travel by bus and show the driver' to avoid repetition?

**Comment by lizziebruce** [comment]
Fixed:

<img width="366" alt="screen shot 2017-06-29 at 14 40 02" src="https://user-images.githubusercontent.com/27814324/27690339-ffc9a568-5cd8-11e7-8cbe-4c3ef1e0e8d7.png">
