### ISSUE TITLE
Users needed to find out if they are eligible to apply but were confused by the statement

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#582]
Some users thought the first sentence implied eligibility if over 60.

Two of those we spoke two read “If you’re over 60 you could get a free bus pass” and then proceeded to start confident that they would be eligible.
![screen shot 2017-06-14 at 14 42 20](https://user-images.githubusercontent.com/24913176/27135158-b4481766-510f-11e7-81ef-fe44d8030f18.png)

Both of these users were 63 years old.

**Comment by lizziebruce** [comment]
Fixed on live prototype:

<img width="814" alt="screen shot 2017-06-29 at 17 32 20" src="https://user-images.githubusercontent.com/27814324/27699069-f9f7533e-5cf0-11e7-9545-96473c3e1c47.png">

**Comment by irinapencheva** [comment]
@lizziebruce - I reread it 3 times until I spotted the difference in the text :D Do you think this will make the difference because it still says '60 or over', which is what drives user to proceed further without checking. Isn't it better if we change the text to '65 or over'?

**Comment by joanneSouthern** [comment]
@irinapencheva all the government and LA sites say 60 and over
https://www.gov.uk/apply-for-elderly-person-bus-pass

**Comment by irinapencheva** [comment]
@joanneSouthern - agreed, but if this prototype is for the English scheme for which eligibility is the state pension age, why not change it and make it less confusing for the user (as was observed in the last round of UR)?

**Comment by lizziebruce** [comment]
@irinapencheva I don't think 65 and over is correct. People can get an older person's bus pass from age 60 depending on when they were born. The female state pension age remember, which changed a few times. 
The UR issue was that the word "could" made people think it was a likelihood rather than a possibility. Changing to "may be able to" though less concise is more clear.

**Comment by irinapencheva** [comment]
@lizziebruce - OK, thanks for pointing out. Agree to changing to 'may be able to'
