### ISSUE TITLE
Accuracy error: Users can't park 24 hours a day (at least in Sunderland)

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#585]
![image](https://user-images.githubusercontent.com/4106955/27221133-71b270ce-527f-11e7-8b88-968b285a7a8c.png)

**Comment by suryanaga** [comment]
![image](https://user-images.githubusercontent.com/4106955/27221378-4b7071ee-5280-11e7-9aeb-52018ca456c7.png)

**Comment by lizziebruce** [comment]
@sanjaypoyzer I'm not sure about if these changes should be made. By having the permit you are unrestricted by the restricted hours, therefore you can park 24 hours a day 7 days a week. I.e. you can park there all the time, not just in the restricted hours.
