### ISSUE TITLE
Make the "scan and upload" option realistic to what councils will actually offer

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#586]
![image](https://user-images.githubusercontent.com/4106955/27221241-c7c6f818-527f-11e7-8f35-7019bc315a0a.png)

**Comment by sanjaypoyzer** [comment]
![image](https://user-images.githubusercontent.com/4106955/27221367-43794e48-5280-11e7-9970-c487e411eb53.png)

**Comment by lizziebruce** [comment]
Content fix applied for Sunderland.

"Provide documentary evidence" seemed ambiguous, so I've labelled the second radio button "Provide proof of identity". It still seems a little unclear. How will they provide evidence, and what are the evidence options? Could you let me know @GWSunderland @EUzkuraityte , as we should include that info in a bullet point.

![screen shot 2017-06-16 at 14 15 55](https://user-images.githubusercontent.com/27814324/27228385-4a727462-529f-11e7-9eee-a18d0af69b7e.png)

**Comment by CTSunderland** [comment]
Hi Lizzie,  sorry for this being vague.  We do not currently ask applicants to provide evidence and are speaking to the service to determine if/how we will be doing this moving forward.  We are happy to use what this has been changed to in our local user research which may help us to shape what we intend to do moving forward.

**Comment by lizziebruce** [comment]
@CTSunderland thanks, I see, that makes sense.

**Comment by suryanaga** [comment]
@CTSunderland Just to clarify, you don't _have_ to offer an online alternative to Verify. If you're _not_ planning to build an online alternative to Verify, this part of your prototype may look more like what's documented in issue #588.

**Comment by CTSunderland** [comment]
We are offering an online alternative to Verify, we're just not certain how/if we are going to request users to supply proof of their identity.

**Comment by suryanaga** [comment]
@CTSunderland Ah ok, understood. In that case the issue is more around the content of this page, specifically the header, as the other route would be more for proving the user's address as opposed to their identity.

**Comment by lizziebruce** [comment]
@CTSunderland Yes – this may be superceded by #588. For this current screen I can change header "Provide proof of identity" to "Provide proof of address"?

**Comment by lizziebruce** [comment]
This has been superceded by #588 

Screenshot with expandable link open:

![screen shot 2017-07-05 at 09 48 55](https://user-images.githubusercontent.com/27814324/27856830-46f2f150-6167-11e7-8e40-d7cfeb831346.png)
