### ISSUE TITLE
Users need to not have to choose unless necessary

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#588]
@sanjaypoyzer @lizziebruce @petegale 
I know that we observed only one user who commented 'Why do I have to choose?' on the check your ID page, but it's obvious that users in general do not like having to make the choice. If we can take away this burden from them,then I think we should do this as much as possible. 

Is there a reason why we could not keep the Verify route as the most prominent option on the page (it is the recommended route anyway) and put the doc upload in 'other ways to apply' (the bit you have to expand)?

The wider question is why do we even have the doc upload option so prominent on the page if this is not the recommended route? 

link to #586 
Adding the link to [Sanjays iteration slides](https://docs.google.com/presentation/d/1xL9vh3SoXQ5LoAheqdSlYQDB_wNgCvCrsHUnzFQzlAo/edit#slide=id.g21153d824a_0_86) for reference

**Comment by lizziebruce** [comment]
thanks @EUzkuraityte. It looks like from the iteration slides there isn't a service standard reason why we couldn't put the doc upload into other ways to apply and as almost every single user we've tested with has veered away from scanning it we would be supporting users to make it easier to do what they want to do. I'll do a version with this change but will wait for Sanjay to get back before adding it to the live prototype.

**Comment by lizziebruce** [comment]
Ok, so here's an idea of what the above could look like. See screenshots below.

PROS - I think it's a robust way to prepare users for the Verify hub element of the journey. Adding @anthonylord and @irinapencheva for info.

CONS - 1. The CTA for scanning is buried in the expandable section. Might not be a problem in itself. 2. But presenting the scan CTA on the same page w/o making clear it's a journey choice risks the user accidentally "choosing" the scan option, if they click on the first links that come up obliviously without reading. So this might not meet service design standards for online journeys. Therefore we might want to consider moving 'Other ways to apply' to a separate page, on a loop like the DOB checker in concessionary travel. Obviously this all needs discussion with @sanjaypoyzer.

**Before**
![screen shot 2017-06-21 at 11 43 27](https://user-images.githubusercontent.com/27814324/27380449-05c0ea48-5677-11e7-879f-5c50e2db5a69.png)
![screen shot 2017-06-21 at 11 43 35](https://user-images.githubusercontent.com/27814324/27380452-07c3ca90-5677-11e7-854e-1e4ba1284bd3.png)

**After**
![screen shot 2017-06-21 at 11 42 56](https://user-images.githubusercontent.com/27814324/27380457-11e08dec-5677-11e7-926b-f57b41d8bffe.png)
![screen shot 2017-06-21 at 11 49 21](https://user-images.githubusercontent.com/27814324/27380617-b96d8eb6-5677-11e7-8948-7f624a08b23d.png)

**Comment by lizziebruce** [comment]
Great call by newest content designer @EUzkuraityte to put the 'Other ways to apply' link below the Continue button (as on Resident start page) :-) 

![screen shot 2017-06-21 at 15 38 56](https://user-images.githubusercontent.com/27814324/27389937-d1979c3c-5697-11e7-845b-3e848af4b07c.png)

I've also tweaked the copy a little more:

![screen shot 2017-06-21 at 15 42 47](https://user-images.githubusercontent.com/27814324/27390128-580db10c-5698-11e7-9050-772264273830.png)

**Comment by lizziebruce** [comment]
Feedback from @irinapencheva this may not be right for CT as the preceding page has numbered steps, and she's hesitant to change CT user journey when it's tested well as is. To clarify, this solution was drafted for PP and hasn't been adapted for CT – it's also a just a possible alternative approach to the prove ID page, which is still to be discussed with service designer.

**Comment by lizziebruce** [comment]
2 more drafts, reducing the copy:

![screen shot 2017-06-23 at 12 06 33](https://user-images.githubusercontent.com/27814324/27480860-d5511ad0-5811-11e7-8972-bb8cff68b277.png)

![screen shot 2017-06-23 at 12 44 01](https://user-images.githubusercontent.com/27814324/27480864-da98e432-5811-11e7-8804-d6fe5f036a8b.png)

**Comment by suryanaga** [comment]
Interested to see how this tests -- In general we know that many people will just click the green button and not read the text, so I'd be worried that might happen in this case. Hopefully the content on that last option is concise enough that they skim through it a bit at least.

Especially interested to see if people click the GOV.UK Verify link, and whether they do so to find out more info or to actually proceed to Verify. Maybe it's even worth making it explicitly "Find out more about GOV.UK Verify."

In any case, it's definitely important we test this version as not all councils will have an online alternative to Verify, so some councils won't be offering a choice like we have at the moment (unless they put text about the offline route in the other radio buttons, which could work).

**Comment by anthonylord** [comment]
Yeah, this is great, it's more like a GOV.UK start page now :)
I see that one of your cons @lizziebruce is that the scanning option is under the expander. Does it need to be an expander? Can't all the other ways be listed under the start button for everyone to see, like this: https://www.gov.uk/check-state-pension. That may help decrease anxiety in those users that tried using Verify in the past but failed, they can see there are other ways to access the service without searching for them under links

**Comment by lizziebruce** [comment]
@anthonylord that sounds interesting. With the Other ways to apply link now below the main CTA it's not so much of a con anymore that scanning is in the expander, as my main worry previously was that people may accidentally end up on the scan route but this shouldn't happen now.
I think the Check your State Pension page works well but worry that on the council pages which have colour in their branding the main CTA may become less noticeable with this presentation. @sanjaypoyzer what do you think? We could see how it tests as is initially (i.e. last screenshot) and observe if users click the other ways to apply link.

**Comment by suryanaga** [comment]
Yeah, let's test it and see what happens

**Comment by lizziebruce** [comment]
These edits to the Hub blue screen pages are likely to also be in place for the next round of testing:

https://docs.google.com/document/d/1FvUf8sT9BbfEe1PsgdBuCWsqs6xMbKs0JDlcDf0JX-A/edit

**Comment by lizziebruce** [comment]
@sanjaypoyzer @EUzkuraityte @petegale 

Screenshots of edits to the Hub blue screens below. Michael Thomas will be switching these on Tuesday morning for the duration of our PP UR day.

NB: DVLA will update to the council name on Tuesday
![screen shot 2017-07-07 at 15 38 55](https://user-images.githubusercontent.com/27814324/27964232-7b6a5fc6-632f-11e7-9068-03f7690a7f2e.png)

![screen shot 2017-07-07 at 10 42 12](https://user-images.githubusercontent.com/27814324/27964238-7faf7170-632f-11e7-8d51-711c9a3dbbd3.png)

![screen shot 2017-07-07 at 10 42 25](https://user-images.githubusercontent.com/27814324/27964256-82daabe4-632f-11e7-9d13-f840e8dee62e.png)

Logic: Visually, apart from being slightly less text, the "major" difference is that the 2nd screen has bullet points. Changing the presentation on the middle screen might make the screens overall a little more interesting to the user, i.e. so that it's not 3 screens with similar looking blocks of text.

**Comment by lizziebruce** [comment]
Following UR we're changing the prove-identity copy back to how it was previously, as the element of choice helps users read and focus. However, scan and upload may not be the best alternative online way to apply. We will look into this further in Beta.

**Comment by lizziebruce** [comment]
Mentioned all of these in the Hub scrutiny meeting today.. They've been recorded for analysis.
