### ISSUE TITLE
Users need to know that their vehicle details are correct

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#592]
![screen shot 2017-06-16 at 13 53 32](https://user-images.githubusercontent.com/20285115/27227422-50d9248a-529b-11e7-8587-a5b38cbb7be8.png)

**Comment by EUzkuraityte** [comment]
link to #145

**Comment by lizziebruce** [comment]
This duplicates #145 so closing this one. This one's referenced on 145.
