### ISSUE TITLE
Users need to know how long a permit they can get before they are presented with the available option

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#599]
Assigning this to Lizzie and Sanjay to advice how we can make it clearer to the user about the length of the permits available to them.

Issues are:
1. From Newcastle Verify UR - users were surprised to see the 3 month permit (when address does not get verified) presented to them when they expected 6 or 12. (see: #591)
2. From Cambridgeshire UR - users were unaware of the 6 vs 12 month option
![screen shot 2017-06-19 at 09 48 42](https://user-images.githubusercontent.com/20285115/27277373-ee9870e0-54d5-11e7-925b-11529e7ee895.png)

**Comment by lizziebruce** [comment]
I'm not sure this is a real user need. 1. Only one user has commented. 2. The 6 and 12 months options are already flagged earlier in the journey, on resident's start page.

Radio buttons - discarding this comment. They are large for a bigger click area therefore better accessibility. See GOV.UK design for radio buttons http://govuk-elements.herokuapp.com/form-elements/#form-radio-buttons
