### ISSUE TITLE
ConTravel (photoguide): Change colour of white bits of images

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#6]

**Comment by suryanaga** [comment]
Would actually be best to provide versions of the images which work on both light and dark backgrounds, so all councils can use them.

**Comment by kateiw** [comment]
In ConTravel there's a bit for upload passport style photograph. When you click through to the example it steps you through how to take a photo  - we need a light and a dark version of each image. Some are already done using code in SVG, but others need to be photoshopped to create a dark one. Match colours to those already done. Look in prototype for ones that need fixing.

**Comment by kateiw** [comment]
@sanjaypoyzer @kaydale are these assets to be reused by LAs to build real services or just for prototyping? If the former we need to to a clean up of all assets to optimise for web.

NB: Ask Ed.
