### ISSUE TITLE
Users need to know how their personal information will be stored and shared

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#601]
See evidence from Cambridgeshire UR:
![screen shot 2017-06-19 at 10 41 22](https://user-images.githubusercontent.com/20285115/27279312-2cc3d502-54dc-11e7-9f0b-2bb8d1711d78.png)

Linking to #452 as this is a similar issue

**Comment by lizziebruce** [comment]
@EUzkuraityte see #41 - we recommend councils include a link to their privacy policy in the footer of every page, many may already be doing this. The GitHub issue gives more details.

Re additional comment, this looks like a one user only comment. We need to ask the question for data protection reasons. As the other part ^^ is a duplicate I'll close this issue.
