### ISSUE TITLE
ConTravel: Add content about linking to replacements service

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#62]

**Comment by kaydale** [comment]
Need to get a rough idea of the different policies & processes are in order to build this. @irinapencheva is this within scope of the pilot?

**Comment by irinapencheva** [comment]
@kaydale Scope of pilot is only new applications, so replacements is not covered in terms of the transformation. But councils should definitely incl. some guidance on what to do if pass is stolen/lost

**Comment by suryanaga** [comment]
Will add something in about contacting council if pass is lost or stolen.

**Comment by irinapencheva** [comment]
@sanjaypoyzer - cool, thanks

**Comment by suryanaga** [comment]
Addressed in PR #154
