### ISSUE TITLE
When no permits are available, users should be put on a waiting list

### ISSUE THREAD

**Issue by petegale** [alphagov/verify-local-patterns#621]
The current service design asks users in this situation if they want to apply for another parking zone. However, these users will not be able to apply for a zone they are not a resident in, and should be put on a waiting list instead.

**Comment by lizziebruce** [comment]
Content fix:

![screen shot 2017-07-05 at 16 56 23](https://user-images.githubusercontent.com/27814324/27873139-e71d1da0-61a2-11e7-9617-854b86e438d2.png)

**Comment by suryanaga** [comment]
@lizziebruce It would be good to be allow users to join the waiting list online. Being able to just put in your address (to match against, avoiding touting wait spots) and method of contact should be all that's needed to join the waiting list.

**Comment by lizziebruce** [comment]
Sure. Will go create this.

**Comment by lizziebruce** [comment]
![screen shot 2017-07-06 at 12 23 59](https://user-images.githubusercontent.com/27814324/27908905-0d08168e-6246-11e7-90d9-5f8a32a6c875.png)

**Comment by suryanaga** [comment]
Looks good, just needs name and contact detail as well. Contact could be a page copied from the end of the journey.

**Comment by lizziebruce** [comment]
@sanjaypoyzer I've added those fields and subheader copy for the contact choice, but can't get the design right. You're probably better placed to sort that out! Have sent you details by DM.

**Comment by lizziebruce** [comment]
@sanjaypoyzer DM from Slack as I know it doesn't store messages for long:

<img width="633" alt="screen shot 2017-07-12 at 10 33 47" src="https://user-images.githubusercontent.com/27814324/28112379-b4aa9138-66f0-11e7-99c4-5ad0aad0eb16.png">

**Comment by EUzkuraityte** [comment]
@lizziebruce @sanjaypoyzer I'm closing this issue as this journey has been created. Let me know if you disagree.
