### ISSUE TITLE
Users with screen readers need to hear the title of the page first 

### ISSUE THREAD

**Issue by irinapencheva** [alphagov/verify-local-patterns#627]
Comments from accessibility review: The title elements aren't front loaded e.g. "Argleton County Council: Apply for an older person's bus pass" would be better if it was "Apply for an older person's bus pass: Argleton County Council" - this helps visually in browsers that display the title in the tab field, but more importantly helps screen reader users understand they are on the page they expected to be on. Many screenreader users skim read and so they might listen just to the word "apply" before arrowing down or tabbing to the page content, which is better than having to listen to "Argleton County Council..." first for each page

**Comment by lizziebruce** [comment]
Removing myself, as believe this is about the Search engine title tag not the H1, which is already "Apply for an older person's bus pass". (The content in the banner page header shouldn't be being read out by a screenreader, it should go straight to the H1.)
