### ISSUE TITLE
ConTravel: Some LAs automatically renew bus passes. How many others do this?

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#63]
Feedback fro Herts

**Comment by joanneSouthern** [comment]
We dont automatically renew bus passes - Northumberland

**Comment by kaydale** [comment]
If you have moved address how does this work? @irinapencheva can you investigate? This should only be automatic if the council is sure they have an up to date address

**Comment by irinapencheva** [comment]
@kaydale - sure, will include as a question to investigate in next round of service pattern comments

**Comment by suryanaga** [comment]
@irinapencheva Any update on this?

**Comment by irinapencheva** [comment]
@sanjaypoyzer - from pilot participants only Herts do automatic renewals, so suggest any changes to service pattern reflect that most LAs don't

**Comment by suryanaga** [comment]
Ok cool, I'll close this issue then and bear it in mind for any future content about renewals
