### ISSUE TITLE
ConTravel: 9. Use bus pass content rewrite needed

### ISSUE THREAD

**Issue by kaydale** [alphagov/verify-local-patterns#66]
Bus passes are a physical plastic card that users can use on any bus in England. They show it to the driver on the way onto the bus.

This is incorrect. An ENCTS pass is a credit card sized smart card produced to the ITSO specification. This can be read electronically by modern ticket machines outside London. In London ENCTS passes are issued as Freedom passes using Oyster technology as well as conforming to the ITSO specification. Ticket machines on London buses do not recognise ITSO ENCTS cards issued outside London; these cards need to be shown to the driver.

**Comment by joanneSouthern** [comment]
Northumberland - we use ITSO specification as mentioned above, saying its a physical plastic card is too simplistic

**Comment by anthonylord** [comment]
We're never going to be able to cover all bus pass formats, so we should make it as general as we can. So change to:

Bus passes are a physical plastic card that users can use on any bus in England. They either have to show it to the driver or scan on a reader when they get onto the bus.
