### ISSUE TITLE
More realistic styling

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#665]
- first line of text being grey
 - green boxes 
 - radio buttons as links

**Comment by suryanaga** [comment]
@artgov and @abibarkeroxfordshire to add any other ways the prototype styling differs from production environment styling.

**Comment by AbiBarkerOxfordshire** [comment]
@sanjaypoyzer Afternoon - I have just had a discussion with Arty about this. He is currently working on the redesign of our public website -a s part of this styling changes will be applied - however at present the styling does reflect both our Goss and Drupal content so any changes made to the prototype would be 'undone' when it is migrated to Live. In light of these we feel it best to leave the styling as it is and await feedback from users - are you happy with this? Thanks, Abi
