### ISSUE TITLE
Application complete page missing title

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#674]
![image](https://user-images.githubusercontent.com/4106955/30268260-12442522-96dd-11e7-8f52-c1e8d2614a7e.png)

**Comment by lizziebruce** [comment]
Title missing, need an H1: “Application complete” 

Prototype
![screen shot 2017-09-12 at 10 55 18](https://user-images.githubusercontent.com/27814324/30321812-4f8637cc-97af-11e7-8a87-f5fc88af1d74.png)

Buckinghamshire
![screen shot 2017-09-12 at 10 56 46](https://user-images.githubusercontent.com/27814324/30321814-5198a784-97af-11e7-92e8-04156e891aff.png)

**Comment by colin2678** [comment]
added to https://trello.com/c/ez88aGnf/13-application-complete

**Comment by BeckiBorastonBucks** [comment]
Done

**Comment by BeckiBorastonBucks** [comment]
Done
