### ISSUE TITLE
Current address form labelling edit needed

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#676]
/current-address
[Bucks prototype page](https://buckinghamshire-self.sandbox.achieveservice.com/en/AchieveForms/?form_uri=sandbox-publish://AF-Process-60ca255d-fc7a-4c4d-a2c3-b022b27de442/AF-Stage-80582df7-cde3-4b58-a51a-3d219a6b75a3/definition.json&redirectlink=%2F&cancelRedirectLink=%2F&category=AF-Category-5f3d517a-d10d-454a-9fce-812c98646009)

I suggest “My address isn’t listed” copy should replace the word “Yes” – so that the check box is meaningfully labelled. There's no need for copy on the left for this row.

![screen shot 2017-09-12 at 12 08 21](https://user-images.githubusercontent.com/27814324/30322943-2302416a-97b3-11e7-8e2a-42d55b822f14.png)

**Comment by colin2678** [comment]
This is a standard subform across the whole of the council. we will investigate the impact of making this change.

**Comment by lizziebruce** [comment]
Thanks Colin.

**Comment by BeckiBorastonBucks** [comment]
Done
