### ISSUE TITLE
Prove-identity page title needs changing

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#677]
Currently the page title on Bucks build is the service name, 'Apply for an older person's bus pass'. As shown by the Argleton prototype, it needs to reflect the current page the user is on. So the title copy should be:

> How should we check your identity?

Prototype (latest design update):

![screen shot 2017-09-12 at 12 22 00](https://user-images.githubusercontent.com/27814324/30323413-093624c0-97b5-11e7-8a3b-e4fae867a4a0.png)

Buckinghamshire:

![screen shot 2017-09-12 at 12 22 07](https://user-images.githubusercontent.com/27814324/30323420-0e8483f4-97b5-11e7-8a07-d02decbf5346.png)

**Comment by colin2678** [comment]
This is inconsistent with other forms on our site and causes confusion as there is no there context on the page to tell you what form you are filling in as we do not have breadcrumbs.

We are investigating a bespoke solution which would hide the H1 and then manually add a breadcrumb to each page (see below). But this may result in more complexity and a greater chance for errors.

https://buckinghamshire-self.sandbox.achieveservice.com/en/AchieveForms/?form_uri=sandbox-publish://AF-Process-60ca255d-fc7a-4c4d-a2c3-b022b27de442/AF-Stage-80582df7-cde3-4b58-a51a-3d219a6b75a3/definition.json&redirectlink=%2F&cancelRedirectLink=%2F&category=AF-Category-5f3d517a-d10d-454a-9fce-812c98646009

**Comment by lizziebruce** [comment]
Thanks for the explanation. I'll refer this to @sanjaypoyzer also as it's become a service design issue.

**Comment by suryanaga** [comment]
Thanks Colin! Would be great to see those breadcrumbs on there :)

**Comment by BeckiBorastonBucks** [comment]
Done

**Comment by lizziebruce** [comment]
Hi @BeckiBorastonBucks and @colin2678 I can see that the radio buttons are at the bottom of the page after both the options now, but the issue with the H1 remains. Is there any update on the bespoke solution for hiding title and adding breadcrumbs that you mentioned above Colin? Thanks.

**Comment by BeckiBorastonBucks** [comment]
Sorry, hadn't republished the form. Try now!

![image](https://user-images.githubusercontent.com/29145984/31993623-af9885c4-b975-11e7-9653-159d856d4c45.png)

**Comment by colin2678** [comment]
We should be able to get the bullets to appear next to the titles, but firmstep will need to provide some javascript to do this.

**Comment by lizziebruce** [comment]
@BeckiBorastonBucks @colin2678 
Fantastic, thanks!
