### ISSUE TITLE
Start page missing line of copy re: out of council area copy

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#678]
Copy line with find your local council link missing: “If you don’t live in Buckinghamshire, find your local council as you’ll need to apply on their website.”

**Comment by colin2678** [comment]
Added to trello board https://trello.com/c/TMaHUMOv/1-start-page

**Comment by lizziebruce** [comment]
Thanks Colin.

**Comment by BeckiBorastonBucks** [comment]
Done
