### ISSUE TITLE
Start page typo

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#680]
Line 2: change “- Y” to “– y”

**Comment by colin2678** [comment]
added to https://trello.com/c/TMaHUMOv/1-start-page

**Comment by BeckiBorastonBucks** [comment]
Done

**Comment by lizziebruce** [comment]
@colin2678 @BeckiBorastonBucks Hi, please could you send me a link to the Start page of your prototype as the one I've been using goes directly to the Verify choice page (and I couldn't find a link that took me to the Start in your Sandbox menu):

https://buckinghamshire-self.sandbox.achieveservice.com/en/AchieveForms/?form_uri=sandbox-publish://AF-Process-af3a3cc9-1a56-4535-9701-87a4e1d0d2b7/AF-Stage-f2b7513c-8133-443a-9820-d317d7282640/definition.json&redirectlink=%2F&cancelRedirectLink=%2F&category=AF-Category-5f3d517a-d10d-454a-9fce-812c98646009

Thanks

**Comment by BeckiBorastonBucks** [comment]
Start page: https://bucks-live.pcg-alias.co.uk/apply-for-an-older-persons-bus-pass/

**Comment by lizziebruce** [comment]
Thanks. @samuelculley also sent me that - unfortunately it leads me to:

<img width="1138" alt="screen shot 2017-10-25 at 10 51 03" src="https://user-images.githubusercontent.com/27814324/31992559-8916fdac-b972-11e7-9c05-efc6d843a5a9.png">

**Comment by lizziebruce** [comment]
Re above - don't worry - I've been able to access using Safari instead of Chrome.

**Comment by BeckiBorastonBucks** [comment]
You can just go to advanced and ignore the warning (!) also.
