### ISSUE TITLE
Start page – Check if you're eligible link

### ISSUE THREAD

**Issue by lizziebruce** [alphagov/verify-local-patterns#711]
1. This should be an inline link rather than a button link, i.e. the style you use for find your local council lower on the page.
2.  The dash afterwards should be an n-dash not a hyphen ( – not - ) if your CMS allows this.

**Comment by EUzkuraityte** [comment]
Hi @lizziebruce could you provide a URL for the page? Is this the CT or PP pilot?

**Comment by lizziebruce** [comment]
This is for Northumberland's concessionary travel prototype, https://form.northumberland.gov.uk/form/launch/concessionary_travel
