### ISSUE TITLE
Journey map 

### ISSUE THREAD

**Issue by BeckiBorastonBucks** [alphagov/verify-local-patterns#749]
The journey map is different to the prototype https://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel/overview/design

- Confirm DOB has now been removed
- Doesn't include stage where address is out of county

**Comment by EUzkuraityte** [comment]
Hi @BeckiBorastonBucks many thanks for flagging these. @sanjaypoyzer @lizziebruce could you update the prototype to reflect this if it hasn't been done yet?

**Comment by lizziebruce** [comment]
@EUzkuraityte thanks I will update the journey map (prototype is up to date)

**Comment by lizziebruce** [comment]
Now updated: https://verify-local-patterns.herokuapp.com/service-patterns/concessionary-travel/overview/design
