### ISSUE TITLE
Add an unsuccessful payment page to the prototype

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#751]
I've just found out that GOV.UK Pay do not provide 'successful / unsuccessful payment' pages. It means we need to account for this in our prototype. Our End confirmation page can serve as a 'successful', but let's have a chat about this. Either way, we need to put together a page that tells the user what should happen when for some reason a payment online cannot be taken.

**Comment by lizziebruce** [comment]
I think councils deal with payment in bespoke local ways. If GOV.UK Pay encourages councils to decide on their own content for unsuccessful pay page it would seem we should also. We'd of course recommend following the GDS design principles and elements: 
https://www.gov.uk/guidance/government-design-principles  
http://govuk-elements.herokuapp.com/ 
Thanks

**Comment by joanneSouthern** [comment]
this will be part of the payment system when its properly intergrated

**Comment by EUzkuraityte** [comment]
sounds great, I'll move this to resolved and close this ticket
