### ISSUE TITLE
Add DVLA API lookup to prototype and pattern

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#78]
Can we change from '7. Enter vehicle details' to '7. Enter vehicle details and additional information'

**Comment by kaydale** [comment]
@EUzkuraityte It links with #79 I'm almost thinking these things might need to be split out across two pages in accordance with the "one thing per page" design principle. 
@kateiw what do you think?

**Comment by kaydale** [comment]
@EUzkuraityte as discussed earlier this can link to https://vehicleenquiry.service.gov.uk/ for the user to find out emissions etc.. 

The details I should add are: 
Cylinder capacity (cc) 
CO₂Emissions 

Anything else?

**Comment by EUzkuraityte** [comment]
@kaydale It's amazing! Do we know what kind of information it returns? 
Does it provide a user's address (just asking because it asks for V5C!)

**Comment by kaydale** [comment]
![vehicle enquiry-service](https://cloud.githubusercontent.com/assets/20561170/22421448/1d310436-e6df-11e6-9dc5-3c828cd98fb8.png)

**Comment by EUzkuraityte** [comment]
awesome thank you! i had a couple of colleagues test it with their info and it didn't work so def need an alternative to manually enter the data.

Also, do we know what v5c adds to the process? does it enhance search and does it return any additional info if entered?

**Comment by suryanaga** [comment]
@EUzkuraityte Do you know if we can talk to someone at DVLA about seeing if there's an API we can pull information from.

If we don't have a direct contact, there seems to be a page about requesting data from DVLA and an email address [here](https://www.gov.uk/data-requests-dvla).

**Comment by davidillsley** [comment]
FYI: https://dvladigital.blog.gov.uk/2016/12/29/next-steps-to-vehicle-enquiry-service-ves-and-developing-an-application-program-interface-api/

**Comment by suryanaga** [comment]
@davidillsley Useful link, thanks!

**Comment by suryanaga** [comment]
Confirmed that we will be probably be using DVLA's API, so will add to prototype.
