### ISSUE TITLE
PP: edit step 7. Enter vehicle details content

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#79]
could you add: at this point the user should also be allowed to select the permit start date and choose the length of permit (if available)

**Comment by kaydale** [comment]
@EUzkuraityte Permit lengths - what form do they take? i.e: 
Select the permit length you need:
- 1 month
- 3 month
- 6  month
- 12 month

Also how many LAs offer permit length/want to offer permit length?
