### ISSUE TITLE
PP: add to step 9. Receive permit confirmation

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#85]
Please add a sentence after this one: 'They should also receive information about how the permit will be enforced (See step 8).'

Please add: 'If the payment cannot be accepted or if the application fails for some reason (i.e. times out) the user should be shown an on-screen message that specifies the next steps a user should take to continue with the application'

--------------

could you also change 'The service should ask' to 'The service may ask'

**Comment by kaydale** [comment]
@EUzkuraityte do you think showing an on-sceen message is specific to 'receive permit' page or is that just more general and deserve it's own section in the pattern?
