### ISSUE TITLE
PP: Step 11: Renewals prototype

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#86]
The link provided is circular. Please can you advise if the prototype page is in development?

**Comment by kaydale** [comment]
@sanjaypoyzer has this open as an issue he is working on (see issue #25) So I don't know if he already has built this but not pushed it to the main prototype. @EUzkuraityte do you think this one could wait until he is back?

**Comment by suryanaga** [comment]
Looks like this was fixed in #53
