### ISSUE TITLE
PP: prototype for Steps 6a & 6b

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#89]
Hi, if possible, could you mock up the prototype for:

See the example page which says what types of permits the user is eligible for (based no their address)
See the example page which says the user is eligible because they are the 1 st applicant of the household.

**Comment by kaydale** [comment]
@EUzkuraityte  eligibility page is here: 
https://verify-local-patterns.herokuapp.com/service-patterns/parking-permit/example-service/eligible?
Do you think the bit about being the 1st applicant is an important details for the pattern?  

Then on what type of permit the user is eligible for - could you give me an example of this content/scenario?

**Comment by EUzkuraityte** [comment]
Hey! I'm happy to leave out the 'being the 1st applicant' detail, as LAs will amend it to their services as appropriate.

as for user being eligible for different types of permits, could you include:

1. an introduction that would say: 'Your home address is eligible for:' - this is to make it clear that the address can get these types of permits, but the user will not necessarily be able to get all of them in the latter stages as some of these types might be used up.
2. a typical selection of: 

- a car park permit
- a residential parking permit (on street)
- 10 visitor permits for your guests

Thank you!
