### ISSUE TITLE
Concessionary travel: Description of physical bus pass

### ISSUE THREAD

**Issue by suryanaga** [alphagov/verify-local-patterns#9]
Paragraph 8 says

Bus passes are a physical plastic card that users can use on any bus in England. They show it to the driver on the way onto the bus.

In London, the pass is an Oyster card which the user scans on a reader.

What it should say is;

Bus passes are a smartcard in all parts of England which are all scanned on the ticket machine on the bus. However, In London, the pass is an Oyster card which can be scanned on the bus, but, bus passes issued in the rest of England will not work on the Oyster scanners and must be shown to the driver.

(N.B. I have no idea if Oyster cards will scan on non-Oyster readers - one of the London boroughs should know this!)

**Comment by irinapencheva** [comment]
Worth including a picture of a sample pass on the confirmation page

**Comment by kateiw** [comment]
@sanjaypoyzer @kaydale we need to get a content designer on this. That replacement paragraph is super confusing.

**Comment by suryanaga** [comment]
@kateiw Yeah, that was just copied from the actual feedback from councils, not a suggestion for actual content. Kay can pull in Ant Lord for help with this if needed.

**Comment by joanneSouthern** [comment]
In Northumberland passes are scanned the bus driver doesnt really get shown them

**Comment by kaydale** [comment]
add stuff about: "how they use their bus pass, bus pass is scanned"
