### ISSUE TITLE
CT: For London boroughs, the eligibility is different from the rest of the country

### ISSUE THREAD

**Issue by ghost** [alphagov/verify-local-patterns#95]
"In London, it might be more helpful to a resident to indicate when they become eligible for the 60+ Oyster, since this is when they first have the opportunity to meet their need for subsidised travel. This might be something like 

""You qualify for a bus pass on 23 March 2021. However, as a London resident you can get a 60+ Oyster card, which also gives you free travel. You qualify for the 60+ Oyster card on 23 March 2017.""

(of course, if they're already old enough for the freedom pass, then the message is a simpler 'You are eligible to apply right now' sort of thing."

**Comment by ghost** [comment]
The page stating that a user is not eligible for a bus pass because of age might make it clearer that the person is not eligible yet. For London again, the first availability will be for the 60+ Oyster card, so this message should similar inform the user of the specific date they become available for the 60+ Oyster card, and provide a call-to-action for the user to go the right page on the TfL site.

**Comment by kaydale** [comment]
@samuelculley Surely this is something specific to London LA's and thus should not be included as the main pattern but this would be a nuance of the pattern.

**Comment by suryanaga** [comment]
Sounds like this could do with a bit more thinking on what should be included.

**Comment by suryanaga** [comment]
@samuelculley @irinapencheva Can we schedule a conversation with Camden about what needs to be in here? It's still not very clear to me.

**Comment by irinapencheva** [comment]
@sanjaypoyzer - can we park this as low priority / icebox for now. We are still not sure about Camden's status so no need to action this
