### ISSUE TITLE
CT: Photo upload page should be more like confirmation page

### ISSUE THREAD

**Issue by ghost** [alphagov/verify-local-patterns#96]
The page a user sees once they've uploaded a photo is effectively the confirmation page for their application, but it doesn't clearly feel like a confirmation page (eg https://govuk-prototype-kit.herokuapp.com/docs/examples/confirmation-page). The emphasised content on the page should refer to the completed application, rather than the uploaded photo.

**Comment by kaydale** [comment]
@samuelculley Yes I agree - it is best to follow the pattern (as closely as possible) that you have linked to given that it is a tried and tested design.

**Comment by suryanaga** [comment]
This is a duplicate of #100
