### ISSUE TITLE
PP: a declaration / disclaimer page to deter users from committing fraud

### ISSUE THREAD

**Issue by EUzkuraityte** [alphagov/verify-local-patterns#98]
Heya,

Would you be able to mock up a carefully worded version of a declaration page that would deter users from committing fraud?

Something similar to the attached? it was requested by Sunderland this morning. 

![screen shot 2017-01-25 at 12 16 47](https://cloud.githubusercontent.com/assets/20285115/22290354/2f904fc8-e2f8-11e6-842f-bb323cd4267e.png)

**Comment by kaydale** [comment]
Sure @EUzkuraityte there are patterns for this on the central gov hackpad so I will use one of those patterns for now - but this would also be good to test in local gov. 

https://designpatterns.hackpad.com/Declarations-RB89Ux2CqUn

**Comment by suryanaga** [comment]
@EUzkuraityte I'd like to understand the need for this a bit more. What kind of fraud is this aiming to prevent? What risks will it mitigate?

**Comment by EUzkuraityte** [comment]
@sanjaypoyzer, we recommend not using V5C or insurance doc upload so we need to propose an alternative way for deterring users from requesting the permit for someone else's car (because these docs provide a connection between the user and the vehicle).

**Comment by suryanaga** [comment]
@EUzkuraityte Why does it matter if people get a permit for someone else's car?

**Comment by EUzkuraityte** [comment]
The explanation I've been given is that in areas where there are waiting lists to get permits for, there cannot be scope to allow for users re-selling their parking permits as they need to be absolutely sure that only people who are genuine residents of the area park their cars in the CPZs. If you want to push back on this, I'm happy to set up some calls with LAs to discuss this! Just let me know

**Comment by suryanaga** [comment]
Yeah I don't think that reasoning is sound.

The permits system should accommodate for residents using their space. If a resident sells their space, they are not going to be using any more space then they would have if they had used it for their own car. For that reason, I am yet to be convinced that there's a need for the user to prove ownership of the car they want a permit for.

**Comment by suryanaga** [comment]
Closing this until more justification for it is given.
